import type { Book } from './books';

export interface GlossaryEntry {
    book: Book;
    term: string;
    abbr?: string;
    definition: string;
    chapters: string[];
    category: string;
}

const glossary: GlossaryEntry[] = [
    // ===== 공정 =====
    { book: 'semi', term: '웨이퍼', abbr: 'Wafer', definition: '반도체 소자를 만드는 원판형 실리콘 기판. 직경 300 mm(12인치)가 현재 표준.', chapters: ['1.1', '1.2'], category: '공정' },
    { book: 'semi', term: '팹', abbr: 'Fab', definition: '반도체 제조 공장(Fabrication Facility). 클린룸 환경에서 웨이퍼를 가공.', chapters: ['1.1', '1.3'], category: '공정' },
    { book: 'semi', term: '파운드리', abbr: 'Foundry', definition: '칩 설계 없이 제조만 전문으로 하는 기업. TSMC, 삼성 파운드리 등.', chapters: ['1.1'], category: '공정' },
    { book: 'semi', term: '팹리스', abbr: 'Fabless', definition: '팹 없이 칩을 설계만 하는 기업. Qualcomm, NVIDIA 등.', chapters: ['1.1'], category: '공정' },
    { book: 'semi', term: '잉곳', abbr: 'Ingot', definition: '단결정 실리콘 원기둥. 초크랄스키(CZ)법으로 성장시킨 후 슬라이싱하여 웨이퍼를 얻는다.', chapters: ['1.2'], category: '공정' },
    { book: 'semi', term: '클린룸', abbr: 'Clean Room', definition: '파티클을 극도로 제어한 무진 공간. 반도체 팹의 핵심 환경.', chapters: ['1.3'], category: '공정' },
    { book: 'semi', term: '산화', abbr: 'Oxidation', definition: '실리콘 표면에 SiO₂(산화막)를 형성하는 공정. 게이트 절연막, 소자 분리에 사용.', chapters: ['1.4'], category: '공정' },
    { book: 'semi', term: '증착', abbr: 'Deposition', definition: '기판 위에 박막을 형성하는 공정. CVD(화학기상증착), PVD(물리기상증착), ALD(원자층증착) 등.', chapters: ['1.4', '1.5'], category: '공정' },
    { book: 'semi', term: 'CVD', abbr: 'Chemical Vapor Deposition', definition: '화학 기상 증착. 가스 반응으로 기판에 박막을 형성.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: 'ALD', abbr: 'Atomic Layer Deposition', definition: '원자층 증착. 한 번에 원자 1층씩 증착하여 극도로 균일한 박막 형성.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: 'PVD', abbr: 'Physical Vapor Deposition', definition: '물리 기상 증착. 스퍼터링 등으로 금속 박막을 증착.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: '식각', abbr: 'Etching', definition: '원하지 않는 부분의 재료를 제거하는 공정. 건식(플라즈마)과 습식(화학 용액)으로 구분.', chapters: ['1.6'], category: '공정' },
    { book: 'semi', term: '플라즈마', abbr: 'Plasma', definition: '이온화된 기체. 건식 식각과 PECVD에서 반응성 이온을 생성하는 핵심 매체.', chapters: ['1.6'], category: '공정' },
    { book: 'semi', term: 'CMP', abbr: 'Chemical Mechanical Planarization', definition: '화학적·기계적 연마로 웨이퍼 표면을 평탄화하는 공정.', chapters: ['1.7'], category: '공정' },
    { book: 'semi', term: '이온 주입', abbr: 'Ion Implantation', definition: '불순물 이온을 가속하여 반도체에 주입하는 도핑 공정.', chapters: ['1.8'], category: '공정' },
    { book: 'semi', term: '어닐링', abbr: 'Annealing', definition: '이온 주입 후 결정 格子를 복구하고 불순물을 활성화하는 열처리 공정.', chapters: ['1.8'], category: '공정' },
    { book: 'semi', term: 'BEOL', abbr: 'Back-End-Of-Line', definition: '트랜지스터 형성 후 금속 배선과 비아를 만드는 후공정.', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: 'FEOL', abbr: 'Front-End-Of-Line', definition: '트랜지스터를 형성하는 전공정(산화, 이온주입, 게이트 형성).', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: '비아', abbr: 'Via', definition: '서로 다른 금속 배선층을 수직으로 연결하는 구멍/플러그.', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: '세정', abbr: 'Cleaning', definition: '웨이퍼 표면의 파티클, 유기물, 금속 오염을 제거하는 공정. SC-1/SC-2 용액 사용.', chapters: ['1.3'], category: '공정' },
    { book: 'semi', term: '패키징', abbr: 'Packaging', definition: '완성된 칩을 외부와 연결하고 보호하는 후공정. 와이어 본딩, 플립칩 등.', chapters: ['1.10'], category: '공정' },
    { book: 'semi', term: '트랜지스터', abbr: 'MOSFET', definition: '반도체의 기본 스위칭 소자. 게이트 전압으로 소스-드레인 간 전류를 제어.', chapters: ['1.1', '1.9'], category: '공정' },

    // ===== 리소그래피 =====
    { book: 'semi', term: '포토리소그래피', abbr: 'Photolithography', definition: '빛을 이용해 마스크의 패턴을 웨이퍼의 포토레지스트에 전사하는 핵심 공정.', chapters: ['2.1'], category: '리소그래피' },
    { book: 'semi', term: '포토레지스트', abbr: 'Photoresist, PR', definition: '빛에 반응하는 감광성 고분자. 노광 후 현상하여 패턴을 형성.', chapters: ['2.2'], category: '리소그래피' },
    { book: 'semi', term: 'EUV', abbr: 'Extreme Ultraviolet', definition: '극자외선(13.5 nm 파장). 7 nm 이하 노드의 핵심 리소그래피 광원.', chapters: ['2.3', '2.12', '5.1'], category: '리소그래피' },
    { book: 'semi', term: 'ArF', definition: '불화아르곤 엑시머 레이저(193 nm 파장). 현재 DUV 리소의 주력 광원.', chapters: ['2.3'], category: '리소그래피' },
    { book: 'semi', term: 'KrF', definition: '크립톤 플루오라이드 엑시머 레이저(248 nm 파장). 성숙 노드에서 사용.', chapters: ['2.3'], category: '리소그래피' },
    { book: 'semi', term: 'NA', abbr: 'Numerical Aperture', definition: '개구수. 렌즈가 빛을 모으는 능력의 척도. NA가 클수록 해상도가 높아진다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: 'DOF', abbr: 'Depth of Focus', definition: '초점 심도. 허용 가능한 포커스 범위. NA가 올라가면 DOF가 줄어든다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: '프로세스 윈도우', abbr: 'Process Window', definition: 'Dose와 Focus의 허용 범위. 이 안에서만 CD 스펙을 만족한다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: 'OPC', abbr: 'Optical Proximity Correction', definition: '광근접보정. 광학 왜곡을 보상하기 위해 마스크 패턴을 미리 변형하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'RET', abbr: 'Resolution Enhancement Technology', definition: '해상도 향상 기술. OPC, PSM, OAI 등의 총칭.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'ILT', abbr: 'Inverse Lithography Technology', definition: '역리소그래피. 원하는 웨이퍼 패턴에서 역으로 최적 마스크를 계산하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'PSM', abbr: 'Phase Shift Mask', definition: '위상 반전 마스크. 인접 패턴에 위상차를 주어 해상도를 향상시키는 기법.', chapters: ['2.7', '2.8'], category: '리소그래피' },
    { book: 'semi', term: 'OAI', abbr: 'Off-Axis Illumination', definition: '비축 조명. 회절차수를 최적으로 포착하기 위해 조명 형태를 변형하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: '마스크', abbr: 'Reticle', definition: '회로 패턴이 새겨진 석영 판. 빛이 통과하여 웨이퍼에 패턴을 전사.', chapters: ['2.8'], category: '리소그래피' },
    { book: 'semi', term: '펠리클', abbr: 'Pellicle', definition: '마스크 표면 보호용 얇은 필름. 파티클이 패턴면에 닿는 것을 방지.', chapters: ['2.8', '2.12'], category: '리소그래피' },
    { book: 'semi', term: 'Overlay', definition: '오버레이. 연속된 리소 레이어 간의 정렬 오차. 서브 나노미터 제어가 필요.', chapters: ['2.9', '2.10'], category: '리소그래피' },
    { book: 'semi', term: 'CPE', abbr: 'Corrections Per Exposure', definition: '노광 필드별 독립 보정. 고차 Overlay 변동을 흡수.', chapters: ['2.10'], category: '리소그래피' },
    { book: 'semi', term: 'CD', abbr: 'Critical Dimension', definition: '핵심 치수(선폭). 패턴의 실제 폭. CD 균일도(CDU)가 수율을 좌우.', chapters: ['2.11'], category: '리소그래피' },
    { book: 'semi', term: 'CDU', abbr: 'CD Uniformity', definition: 'CD 균일도. 웨이퍼 내/간, 필드 내/간, 로트 간 변동을 계층적으로 분해하여 관리.', chapters: ['2.11'], category: '리소그래피' },
    { book: 'semi', term: 'MEEF', abbr: 'Mask Error Enhancement Factor', definition: '마스크 오차가 웨이퍼에서 얼마나 증폭되는지 나타내는 계수.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'CD-SAXS', abbr: 'Small-Angle X-ray Scattering', definition: 'X선 소각 산란 기반 CD 측정. 3D 패턴 프로파일을 비파괴로 계측.', chapters: ['2.12'], category: '리소그래피' },
    { book: 'semi', term: '확률적 결함', abbr: 'Stochastic Defect', definition: 'EUV 광자 수 부족으로 발생하는 통계적 패턴 결함. Shot Noise에 의한 랜덤 변동.', chapters: ['2.12'], category: '리소그래피' },
    { book: 'semi', term: '멀티패터닝', abbr: 'Multi-Patterning', definition: 'EUV 이전에 미세 피치를 달성하기 위해 여러 번 노광하는 기법. LELE, SADP 등.', chapters: ['2.13'], category: '리소그래피' },
    { book: 'semi', term: 'SADP', abbr: 'Self-Aligned Double Patterning', definition: '자기 정렬 이중 패터닝. 스페이서를 이용해 피치를 절반으로 줄이는 기법.', chapters: ['2.13'], category: '리소그래피' },
    { book: 'semi', term: 'High-NA', definition: 'NA 0.55의 차세대 EUV 시스템. 비등방(Anamorphic) 광학계 사용.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: 'DSA', abbr: 'Directed Self-Assembly', definition: '블록 공폴리머의 자기 조립을 이용한 차세대 패터닝 기술.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: 'NIL', abbr: 'Nanoimprint Lithography', definition: '나노임프린트. 몰드로 물리적 압착하여 패턴을 전사. 광학 불필요.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: '회절', abbr: 'Diffraction', definition: '빛이 패턴 가장자리에서 퍼지는 현상. 리소그래피 해상도의 근본적 제한 요인.', chapters: ['2.6', '2.7'], category: '리소그래피' },
    { book: 'semi', term: '보성 곡선', abbr: 'Bossung Curve', definition: 'Focus에 따른 CD 변화를 보여주는 곡선. 프로세스 윈도우 분석의 핵심 도구.', chapters: ['2.6'], category: '리소그래피' },

    // ===== 수율/계측 =====
    { book: 'semi', term: '수율', abbr: 'Yield', definition: '웨이퍼에서 양품 칩의 비율. 반도체 비즈니스의 핵심 지표.', chapters: ['3.1'], category: '수율/계측' },
    { book: 'semi', term: 'SPC', abbr: 'Statistical Process Control', definition: '통계적 공정 관리. 관리도로 공정 안정성을 실시간 감시.', chapters: ['3.2'], category: '수율/계측' },
    { book: 'semi', term: 'FDC', abbr: 'Fault Detection & Classification', definition: '장비 센서 데이터로 이상을 자동 탐지하고 분류하는 시스템.', chapters: ['3.3'], category: '수율/계측' },
    { book: 'semi', term: 'APC', abbr: 'Advanced Process Control', definition: '고급 공정 제어. R2R(Run-to-Run) 피드백/피드포워드로 공정을 실시간 보정.', chapters: ['3.5'], category: '수율/계측' },
    { book: 'semi', term: 'VM', abbr: 'Virtual Metrology', definition: '가상 계측. 실측 없이 FDC 데이터로 공정 결과를 예측하는 ML 모델.', chapters: ['3.4'], category: '수율/계측' },
    { book: 'semi', term: 'R2R', abbr: 'Run-to-Run', definition: '웨이퍼(또는 Lot) 단위로 공정 조건을 피드백 보정하는 제어 방식.', chapters: ['3.5'], category: '수율/계측' },
    { book: 'semi', term: 'CD-SEM', definition: '주사 전자 현미경 기반 선폭(CD) 측정 장비.', chapters: ['3.6'], category: '수율/계측' },
    { book: 'semi', term: 'OCD', abbr: 'Optical Critical Dimension', definition: '광학 기반 CD 측정. 산란광 분석으로 비파괴 고속 측정.', chapters: ['3.6'], category: '수율/계측' },
    { book: 'semi', term: 'ADC', abbr: 'Automatic Defect Classification', definition: '자동 결함 분류. SEM 이미지에서 결함 유형을 자동 판별.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: '웨이퍼맵', abbr: 'Wafer Map', definition: '웨이퍼 내 다이별 결함/계측 분포를 2D로 시각화한 맵. 공간 패턴으로 원인 분석.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: 'ADI', abbr: 'After Develop Inspection', definition: '현상 후 검사. 리소 패턴의 결함을 식각 전에 조기 탐지.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: 'AEI', abbr: 'After Etch Inspection', definition: '식각 후 검사. 최종 패턴의 결함 검출.', chapters: ['3.7'], category: '수율/계측' },

    // ===== AI/ML =====
    { book: 'semi', term: 'XGBoost', definition: 'Gradient Boosted Decision Trees. 반도체 VM/FDC에서 가장 많이 쓰이는 ML 알고리즘.', chapters: ['4.2'], category: 'AI/ML' },
    { book: 'semi', term: 'SHAP', abbr: 'SHapley Additive exPlanations', definition: '피처의 기여도를 정량적으로 분해하는 모델 해석 기법.', chapters: ['4.2', '4.4'], category: 'AI/ML' },
    { book: 'semi', term: '피처 엔지니어링', abbr: 'Feature Engineering', definition: '도메인 지식 기반으로 ML 입력 피처를 설계하는 과정. Focus², Dose×두께 등.', chapters: ['4.2'], category: 'AI/ML' },
    { book: 'semi', term: '시간 기반 분할', abbr: 'Temporal Split', definition: '학습/검증 데이터를 시간 순서로 분할하여 데이터 누수를 방지하는 방법.', chapters: ['4.3'], category: 'AI/ML' },
    { book: 'semi', term: 'RI', abbr: 'Reliability Index', definition: '신뢰 지수. VM 예측의 신뢰도를 0~1로 정량화. RI > 0.7이면 예측 신뢰.', chapters: ['4.3'], category: 'AI/ML' },
    { book: 'semi', term: '이상 탐지', abbr: 'Anomaly Detection', definition: '정상에서 벗어난 데이터를 자동 감지. Autoencoder, Isolation Forest 등 사용.', chapters: ['3.3', '4.6'], category: 'AI/ML' },
    { book: 'semi', term: 'MLOps', definition: 'ML 모델의 학습→배포→모니터링→재학습 전체 생명주기 관리 체계.', chapters: ['4.5'], category: 'AI/ML' },
    { book: 'semi', term: 'CNN', abbr: 'Convolutional Neural Network', definition: '합성곱 신경망. 웨이퍼맵 패턴 분류, OPC 가속 등에 사용.', chapters: ['4.6'], category: 'AI/ML' },
    { book: 'semi', term: 'LSTM', abbr: 'Long Short-Term Memory', definition: '장단기 기억 네트워크. FDC Trace의 시계열 패턴 학습에 사용.', chapters: ['4.6'], category: 'AI/ML' },
    { book: 'semi', term: '전이 학습', abbr: 'Transfer Learning', definition: '한 팹/장비에서 학습한 모델을 다른 팹/장비에 적응시키는 기법.', chapters: ['4.7'], category: 'AI/ML' },
    { book: 'semi', term: 'Federated Learning', definition: '연합 학습. 데이터를 공유하지 않고 모델 파라미터만 교환하여 학습.', chapters: ['4.7'], category: 'AI/ML' },
    { book: 'semi', term: 'RL', abbr: 'Reinforcement Learning', definition: '강화 학습. 에이전트가 환경과 상호작용하며 보상을 최대화하는 정책을 학습.', chapters: ['4.8'], category: 'AI/ML' },
    { book: 'semi', term: 'Bayesian Optimization', abbr: 'BO', definition: '베이지안 최적화. 서로게이트 모델(GP)과 획득 함수로 효율적 전역 최적화.', chapters: ['4.8'], category: 'AI/ML' },
    { book: 'semi', term: 'LLM', abbr: 'Large Language Model', definition: '대규모 언어 모델. GPT 등. 반도체에서는 엔지니어 어시스턴트로 활용.', chapters: ['4.9'], category: 'AI/ML' },
    { book: 'semi', term: 'SMILE', definition: 'Smart Manufacturing Intelligence & Learning Engine. 반도체 AI 통합 파이프라인.', chapters: ['4.10'], category: 'AI/ML' },
    { book: 'semi', term: '디지털 트윈', abbr: 'Digital Twin', definition: '실제 팹/장비의 가상 복제본. 물리+ML 모델로 시뮬레이션과 최적화.', chapters: ['5.2'], category: 'AI/ML' },
    { book: 'semi', term: 'Foundation Model', definition: '대규모 사전학습 모델. 반도체 Foundation Model은 여러 팹 데이터로 사전학습 후 소량 적응.', chapters: ['5.2'], category: 'AI/ML' },
    { book: 'semi', term: '데이터 드리프트', abbr: 'Data Drift', definition: '시간에 따라 입력 데이터의 분포가 변하는 현상. 모델 재학습 트리거.', chapters: ['4.5'], category: 'AI/ML' },

    // ===== 장비/기업 =====
    { book: 'semi', term: 'ASML', definition: '네덜란드 반도체 노광장비 기업. EUV 스캐너 독점 공급.', chapters: ['2.4', '2.12'], category: '장비/기업' },
    { book: 'semi', term: '스캐너', abbr: 'Scanner', definition: '스텝 앤 스캔(Step & Scan) 방식의 노광 장비. 슬릿으로 마스크를 주사하며 노광.', chapters: ['2.4'], category: '장비/기업' },
    { book: 'semi', term: 'KLA', definition: '반도체 검사/계측 장비 기업. 결함 검사와 패턴 인식 분야 선도.', chapters: ['3.7', '5.3'], category: '장비/기업' },
    { book: 'semi', term: 'TSMC', definition: '대만 파운드리 기업. 세계 최대 반도체 위탁 생산.', chapters: ['1.1', '5.3'], category: '장비/기업' },
    { book: 'semi', term: 'cuLitho', definition: 'NVIDIA의 GPU 기반 OPC/리소 시뮬레이션 가속 플랫폼. 40배 이상 속도 향상.', chapters: ['2.7', '5.2'], category: '장비/기업' },
    { book: 'semi', term: 'Applied Materials', abbr: 'AMAT', definition: '세계 최대 반도체 장비 기업. 식각, 증착, CMP 장비 공급.', chapters: ['5.3'], category: '장비/기업' },

    // ===== stats 자리 자동 추출 + definition v2 =====
    { book: 'stats', term: '가중평균', abbr: 'Weighted Mean', definition: '각 값에 중요도를 나타내는 가중치를 곱한 뒤 가중치 합으로 나눈 평균으로, 클래스 불균형 처리·앙상블·Attention 등 ML 전반에서 핵심적으로 사용된다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '비강건', abbr: 'Non-robust', definition: '통계량이 이상치 같은 소수의 극단값에 의해 크게 흔들리는 성질을 말한다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '왜도', abbr: 'Skewness', definition: '분포의 비대칭 정도를 표준화된 값의 세제곱 평균으로 수치화한 지표로, 부호와 크기를 통해 어느 쪽 꼬리가 얼마나 무거운지를 나타낸다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '후버 손실', abbr: 'Huber Loss', definition: '작은 오차에는 제곱(MSE), 큰 오차에는 절대값(MAE)을 적용하여 두 손실함수의 장점을 절충한 회귀 손실함수이다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '변동계수', abbr: 'Coefficient of Variation, CV', definition: '표준편차를 평균으로 나눈 값(s/x̄)으로, 단위가 다른 변수들의 상대적 변동성을 비교할 수 있게 해주는 무차원 지표이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '분산', abbr: 'Variance', definition: '데이터가 평균에서 얼마나 떨어져 있는지를 제곱 편차의 평균으로 나타낸 값으로, 분포의 흩어진 정도를 수치화한 지표이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '중심극한정리', abbr: 'CLT', definition: '독립인 표본들의 평균이 가지는 분산이 표본 크기 n에 반비례하여 σ²/n로 줄어든다는 통계학의 기본 정리이다.', chapters: ['1.2', '2.4'], category: '기타' },
    { book: 'stats', term: '평균절대편차', abbr: 'Mean Absolute Deviation, MAD', definition: '각 데이터가 평균에서 떨어진 거리의 절대값을 평균낸 값으로, 평균에서의 평균적인 이탈 정도를 나타내는 산포 측도이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '분위 회귀', abbr: 'Quantile Regression', definition: '조건부 평균이 아닌 조건부 백분위수(예: p90, p95)를 직접 예측하는 회귀 기법으로, 핀볼 손실(Pinball Loss)을 손실함수로 사용한다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제1사분위수', abbr: 'Q1', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 25% 지점에 해당하는 값으로, 25번째 백분위수(p25)와 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제2사분위수', abbr: 'Q2', definition: '데이터를 크기 순으로 정렬했을 때 아래에서 50% 지점에 해당하는 값으로, 중앙값과 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제3사분위수', abbr: 'Q3', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 75% 지점에 해당하는 값으로, 75번째 백분위수와 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '핀볼 손실', abbr: 'Pinball Loss', definition: '분위 회귀에서 사용하는 손실함수로, 과소예측과 과대예측에 비대칭적인 가중치(τ와 1-τ)를 부여하여 조건부 백분위수를 추정하도록 한다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: 'p번째 백분위수', abbr: 'p-th percentile', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 p%에 해당하는 값이다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '공분산', abbr: 'Covariance', definition: '공분산은 두 변수가 평균을 기준으로 같은 방향으로 함께 변하는 경향을 측정하는 값으로, 양수면 같은 방향, 음수면 반대 방향의 움직임을 나타낸다.', chapters: ['1.4'], category: '기타' },
    { book: 'stats', term: '상호정보량', abbr: 'Mutual Information, MI', definition: '정보이론에 기반하여 X를 알았을 때 Y에 대한 불확실성이 얼마나 줄어드는지를 측정하는 지표로, 선형·비선형·단조·비단조를 가리지 않고 모든 형태의 의존 관계를 포착한다.', chapters: ['1.4', '6.3'], category: '기타' },
    { book: 'stats', term: '바이올린 플롯', abbr: 'Violin Plot', definition: '박스플롯의 요약 통계 위에 KDE를 겹쳐서 분포의 형태까지 함께 보여주는 시각화 도구이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: '커널 밀도 추정', abbr: 'Kernel Density Estimation, KDE', definition: '각 데이터 포인트에 부드러운 커널(보통 가우시안)을 얹고 합산하여 연속적인 밀도 곡선을 추정하는 방법이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: 'QQ플롯', abbr: 'Quantile-Quantile Plot', definition: '데이터의 표본 분위수와 정규분포의 이론 분위수를 좌표로 찍어, 데이터가 정규분포에서 얼마나 그리고 어디서 벗어나는지를 시각적으로 보여주는 정규성 판단 도구이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: '베이지안', abbr: 'Bayesian', definition: '확률을 불확실성에 대한 주관적 믿음의 정도로 해석하는 통계학 학파이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '빈도주의', abbr: 'Frequentist', definition: '확률을 무한히 반복된 시행에서의 상대 빈도로 정의하는 통계학 학파이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '사전확률', abbr: 'Prior', definition: '데이터를 관측하기 전에 가지고 있던 가설에 대한 초기 믿음의 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '사후확률', abbr: 'Posterior', definition: '데이터를 관측한 후 베이즈 정리로 업데이트된 가설의 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '여사건의 법칙', abbr: 'Complement Rule', definition: '어떤 사건 A가 일어나지 않을 확률은 1에서 A가 일어날 확률을 뺀 값과 같다는 법칙으로, 즉 P(A^c) = 1 - P(A)이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '우도', abbr: 'Likelihood', definition: '특정 가설이나 모수가 참이라고 가정했을 때 관측된 데이터가 나타날 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '콜모고로프 공리', abbr: 'Kolmogorov Axioms', definition: '확률론 전체를 떠받치는 세 가지 기본 규칙(비음성, 정규화, 가법성)으로, 모든 확률 법칙이 여기서 유도된다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '경험적 위험 최소화', abbr: 'Empirical Risk Minimization, ERM', definition: '알 수 없는 기대 손실 대신 학습 데이터에 대한 경험적 손실(표본 평균)을 최소화하여 모델을 학습시키는 원리이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '누적분포함수', abbr: 'CDF, Cumulative Distribution Function', definition: '확률변수가 특정 값 이하일 확률을 그 값의 함수로 나타낸 것으로, $F(x) = P(X \\leq x)$로 정의되며 이산·연속 모두에 적용 가능한 단조 비감소 함수이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '코시 분포', abbr: 'Cauchy distribution', definition: '꼬리가 매우 두꺼워 적분이 발산하기 때문에 기댓값이 존재하지 않는 연속 확률분포로, 표본 크기를 아무리 늘려도 표본 평균이 특정 값으로 수렴하지 않는다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률밀도함수', abbr: 'PDF, Probability Density Function', definition: '연속 확률변수에서 특정 값 근처의 확률 밀도를 나타내는 함수로, 구간에 대해 적분하면 그 구간에서 값이 나올 확률이 된다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률변수', abbr: 'Random Variable', definition: '표본공간의 각 결과를 실수에 대응시키는 함수로, 각 결과에 숫자를 부여하는 규칙이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률질량함수', abbr: 'PMF, Probability Mass Function', definition: '이산 확률변수에서 각 값 x에 대해 그 값이 나올 확률 P(X = x)를 직접 지정하는 함수이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '베르누이 분포', abbr: 'Bernoulli Distribution', definition: '결과가 성공(1) 또는 실패(0) 두 가지로만 나타나는 시행을 모델링하는 확률분포로, 단일 파라미터 p에 의해 P(X=1)=p, P(X=0)=1-p로 결정된다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '최대우도추정', abbr: 'Maximum Likelihood Estimation, MLE', definition: '관측된 데이터가 나올 확률(우도)을 최대화하는 분포의 파라미터를 찾아 추정하는 통계적 방법이다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '포아송 회귀', abbr: 'Poisson Regression', definition: '카운트 데이터를 예측하기 위해 타겟이 포아송 분포를 따른다고 가정하고 로그 링크 함수로 평균을 모델링하는 일반화 선형 회귀 기법이다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '라플라스 분포', abbr: 'Laplace Distribution', definition: '평균을 중심으로 양쪽으로 대칭인 지수분포 형태의 확률분포로, 뾰족한 봉우리를 가져 L1 정규화(Lasso)의 사전분포로 사용된다.', chapters: ['2.4'], category: '기타' },
    { book: 'stats', term: '부트스트랩', abbr: 'Bootstrap', definition: '원본 데이터에서 복원 추출로 같은 크기의 새 데이터셋을 반복 생성하여, 통계량의 표본 분포를 시뮬레이션으로 직접 근사하는 기법이다.', chapters: ['2.5'], category: '기타' },
    { book: 'stats', term: '표본 분포', abbr: 'sampling distribution', definition: '어떤 통계량(평균, 중앙값, 회귀 계수 등)을 동일한 크기의 표본에서 반복적으로 계산했을 때 그 값들이 이루는 확률 분포이다.', chapters: ['2.5', '3.1'], category: '기타' },
    { book: 'stats', term: '표준오차', abbr: 'Standard Error, SE', definition: '표본 평균의 흩어짐을 나타내는 척도로, 모표준편차를 표본 크기의 제곱근으로 나눈 값(σ/√n)이며 평균 추정의 정밀도를 의미한다.', chapters: ['2.5'], category: '기타' },
    { book: 'stats', term: '몬테카를로', abbr: 'Monte Carlo', definition: '해석적으로 풀기 어려운 적분이나 기댓값을 난수 표본의 평균으로 근사하는 기법이며, 큰 수의 법칙(LLN)이 그 이론적 근거이다.', chapters: ['2.6'], category: '기타' },
    { book: 'stats', term: '모수', abbr: 'Parameter', definition: '모집단의 특성을 나타내는 고정된 상수로, 일반적으로 그리스 문자로 표기하며 표본에서 계산한 통계량으로 추정한다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '모집단', abbr: 'Population', definition: '관심의 대상이 되는 전체 집합으로, 모든 가능한 관측치를 포괄하며 대부분 직접 관측할 수 없다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '불편추정량', abbr: 'unbiased estimator', definition: '추정량의 기댓값이 추정하려는 모수와 일치하는, 즉 평균적으로 참값을 맞히는 추정량이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '통계량', abbr: 'Statistic', definition: '표본에서 계산한 값으로, 모수를 추정하는 데 사용되는 확률변수이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '통계적 추론', abbr: 'statistical inference', definition: '관측한 표본 데이터를 바탕으로 직접 관측할 수 없는 모집단의 특성을 추측하는 통계적 방법론이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '표본', abbr: 'Sample', definition: '모집단에서 뽑은 부분집합으로, 우리가 실제로 관측하고 분석에 사용하는 데이터이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '구간추정', abbr: 'Interval Estimation', definition: '모수의 진짜 값이 포함될 것으로 기대되는 범위를 신뢰구간으로 제시하여 추정의 불확실성을 함께 보고하는 방법이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '신뢰구간', abbr: 'Confidence Interval', definition: '모수의 참값이 포함될 것으로 기대되는 범위를 특정 확률 수준과 함께 제시하여, 추정의 불확실성을 정량적으로 표현하는 구간이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '신용구간', abbr: 'credible interval', definition: '베이즈 통계에서 모수에 부여된 사후확률분포를 바탕으로 "모수가 특정 범위에 있을 확률이 95%"라고 직접 해석할 수 있는 구간이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '예측구간', abbr: 'Prediction Interval', definition: '새로운 개별 관측값이 포함될 것으로 예상되는 범위로, 모수 추정의 불확실성에 데이터 자체의 변동성까지 더해 계산하므로 항상 신뢰구간보다 넓다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '가설검정', abbr: 'Hypothesis Testing', definition: '관측된 차이가 우연으로 설명 가능한지를 귀무가설을 기각하는 방식으로 판단하는 통계적 추론 프레임워크이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '검정 통계량', abbr: 'test statistic', definition: '귀무가설 하에서 관측 결과가 얼마나 극단적인지를 하나의 숫자로 요약한 값이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '검정력 분석', abbr: 'power analysis', definition: '원하는 검정력을 달성하기 위해 필요한 표본 크기를 실험 전에 계산하는 절차이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '귀류법', abbr: 'proof by contradiction', definition: '어떤 명제를 증명하기 위해 그 부정을 가정한 뒤 모순을 이끌어내어 원래 명제를 간접적으로 증명하는 논증 방법이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '사후 검정력 분석', abbr: 'post-hoc power analysis', definition: '실험을 수행한 후에 관측된 효과 크기와 표본 크기로 검정력을 계산하는 분석으로, p-value의 변환에 불과하여 새로운 정보를 제공하지 않는다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '제1종 오류', abbr: 'Type I', definition: '귀무가설이 참(효과 없음)인데도 이를 기각하여 효과가 있다고 잘못 판단하는 오류로, 그 확률은 유의수준 α와 같다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '제2종 오류', abbr: 'Type II', definition: '귀무가설이 거짓(실제로 효과가 있음)임에도 불구하고 이를 기각하지 못해 효과가 없다고 잘못 판단하는 오류로, 확률은 β로 표기하며 ML의 False Negative에 해당한다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '효과 크기', abbr: 'Effect Size', definition: '두 그룹 간 차이의 크기를 표준화하여 나타낸 값으로, 검정력에 직접적인 영향을 주는 핵심 요인이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '단측검정', abbr: 'one-sided test', definition: '가설의 방향(예: μ_B > μ_A 또는 μ_B < μ_A)을 사전에 지정하여 한쪽 방향의 차이만 검정하는 방식이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '양측검정', abbr: 'two-sided test', definition: '두 집단의 평균이 방향에 관계없이 다른지(μ_A ≠ μ_B) 검정하는 방식이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '짝 내 변동', abbr: 'within-pair variation', definition: '대응표본 내에서 짝지어진 두 관측값 사이의 차이로 인한 변동으로, 대응 검정이 통계적 신호로 사용하는 변동 성분이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '합동 비율', abbr: 'pooled proportion', definition: '두 그룹의 전환율이 같다는 귀무가설 하에서 전체 데이터를 합쳐 추정한 하나의 비율이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: 'z-검정', abbr: 'z-test', definition: '모표준편차 σ를 안다고 가정하고, 검정 통계량 $z = (\\bar{x} - \\mu_0) / (\\sigma/\\sqrt{n})$가 표준정규분포 $N(0,1)$을 따른다는 성질을 이용해 모평균에 대한 가설을 검정하는 방법이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '분모', abbr: 'MSW', definition: 'ANOVA F-통계량의 분모에 해당하는 그룹 내 평균 제곱(Mean Square Within)으로, 각 데이터가 자기 그룹 평균에서 벗어난 정도를 나타내는 그룹 내 노이즈를 측정한다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '분산분석', abbr: 'Analysis of Variance, ANOVA', definition: '셋 이상의 그룹 평균을 동시에 비교하여 집단 간 차이가 통계적으로 유의한지 검정하는 방법으로, t-검정을 반복할 때 누적되는 거짓 양성 문제를 피하기 위해 사용한다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '분자', abbr: 'MSB', definition: 'ANOVA F-통계량의 분자에 해당하는 평균 제곱 그룹 간 변동(Mean Square Between)으로, 각 그룹 평균이 전체 평균에서 얼마나 떨어져 있는지를 나타내며 SSB를 자유도 k-1로 나눈 값이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '사후 검정', abbr: 'post-hoc test', definition: 'ANOVA 등에서 전체 차이가 유의미하다고 판정된 후, 구체적으로 어떤 그룹 쌍이 서로 다른지를 식별하기 위해 수행하는 추가 통계 검정이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'ANOVA', abbr: 'Analysis of Variance', definition: '세 개 이상 그룹의 평균이 모두 같은지를 그룹 간 변동과 그룹 내 변동의 비(F-통계량)로 한 번에 검정하는 방법이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SSB', abbr: 'Between', definition: '그룹 간 평균 차이에 의해 발생하는 분산으로, 각 그룹 평균과 전체 평균의 편차 제곱합에 그룹 크기를 가중하여 계산한다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SST', abbr: 'Total', definition: '전체 데이터가 전체 평균으로부터 벗어난 정도를 제곱합으로 나타낸 값으로, ANOVA에서 전체 분산을 의미한다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SSW', abbr: 'Within', definition: '같은 그룹 내 개별 데이터들이 그룹 평균으로부터 벗어난 정도를 합한 값으로, 그룹 내부의 변동을 나타낸다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '가족별 오류율', abbr: 'Family-Wise Error Rate, FWER', definition: '여러 번의 가설검정을 수행할 때 그중 하나라도 거짓 양성이 발생할 확률로, 독립인 경우 1 - (1-α)^m로 계산된다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '기댓값', abbr: 'E', definition: '확률변수가 반복 실험에서 평균적으로 취하는 값으로, 분모가 0이 되는 경우처럼 비율이 정의되지 않는 상황도 자연스럽게 처리할 수 있게 해주는 통계적 평균 개념이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '다중검정 문제', abbr: 'Multiple Testing Problem', definition: '여러 번의 통계 검정을 동시에 수행할 때, 각 검정의 거짓 양성 확률이 누적되어 우연히 유의미한 결과가 나올 가능성이 증가하는 문제이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '위발견율', abbr: 'False Discovery Rate, FDR', definition: '유의미하다고 판정한 검정들 중에서 거짓 양성이 차지하는 비율의 기댓값으로, 다중검정에서 발견 목록의 품질을 통제하기 위한 지표이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '가우스-마르코프 정리', abbr: 'Gauss-Markov Theorem', definition: '선형성·오차의 기댓값 0·등분산·무상관이라는 네 가지 가정 하에서 OLS 추정량이 모든 선형 불편추정량 중 분산이 가장 작다(BLUE)는 것을 보장하는 정리이다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '닫힌 형태', abbr: 'closed-form', definition: '반복적 최적화 없이 유한한 수학 연산만으로 정확한 해를 한 번에 구할 수 있는 형태이다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '정규방정식', abbr: 'normal equation', definition: '선형회귀에서 잔차제곱합(RSS)을 최소화하는 회귀계수의 해를 직접 구하는 식 $X^TX\\beta = X^Ty$로, 잔차 벡터가 설명변수 행렬 $X$의 열공간에 직교한다는 기하학적 의미에서 "normal(직교)"이라 불린다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '최소제곱법', abbr: 'Ordinary Least Squares, OLS', definition: '잔차 제곱합(RSS)을 최소화하는 회귀 계수를 추정하는 방법으로, 정규 노이즈 가정 하에서 최대우도추정(MLE)과 동치이다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: 'BLUE', abbr: 'Best Linear Unbiased Estimator', definition: '가우스-마르코프 가정 하에서 모든 선형 불편추정량 중 분산이 가장 작은(가장 효율적인) 추정량으로, OLS 추정량이 이 성질을 만족한다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '결정 경계', abbr: 'decision boundary', definition: '분류 모델에서 예측 클래스가 바뀌는 경계로, 로지스틱 회귀에서는 $P(Y=1)=0.5$가 되는 지점(즉 $w^Tx + b = 0$)에 해당하는 피처 공간상의 초평면이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '보정', abbr: 'Calibration', definition: '모델이 출력한 확률값이 실제 관측 빈도로서의 진짜 확률에 얼마나 가까운지를 나타내는 속성이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '소프트맥스', abbr: 'Softmax', definition: 'K개의 로짓을 각각 지수화한 후 전체 합으로 나누어, 모든 클래스의 확률이 0~1이고 합이 1이 되도록 변환하는 다중 클래스 활성화 함수이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '오즈비', abbr: 'Odds Ratio', definition: '로지스틱 회귀에서 설명변수가 1 단위 증가할 때 오즈가 몇 배로 변하는지를 나타내는 값으로, 회귀계수의 지수 변환(e^β)으로 계산된다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '카테고리 분포', abbr: 'Categorical Distribution', definition: 'K개의 상호 배타적 클래스 중 하나가 발생할 확률을 나타내는 이산 확률 분포로, 다중 클래스 분류에서 소프트맥스 출력의 기반이 되며 음의 로그 가능도가 Categorical Cross-Entropy 손실로 이어진다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '피셔 정보 행렬', abbr: 'Fisher Information Matrix', definition: '로그가능도 함수의 2차 미분에 대한 기댓값으로 정의되며, MLE 추정량의 점근적 분산(역행렬이 공분산 행렬)을 결정하는 행렬이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '가우시안', abbr: 'Gaussian', definition: '평균과 분산으로 특징지어지는 종 모양의 연속 확률분포로, 베이즈 회귀에서 계수에 0 근처의 값이 나타날 것이라는 사전 믿음을 표현하는 데 사용된다.', chapters: ['4.4'], category: '기타' },
    { book: 'stats', term: 'MAP', abbr: 'L2', definition: '가우시안 사전분포 하에서 사후확률을 최대화하는 추정으로, 노이즈 분산과 사전분산의 비($\\lambda = \\sigma^2/\\tau^2$)를 정규화 강도로 갖는 Ridge 회귀와 동일하다.', chapters: ['4.4'], category: '기타' },
    { book: 'stats', term: '이중 하강', abbr: 'Double Descent', definition: '모델 복잡도를 보간 임계점 너머로 극단적으로 키우면 테스트 오차가 다시 감소하여, 전통적인 U자 곡선을 벗어나는 현상이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: '편향-분산 분해', abbr: 'Bias-Variance Decomposition', definition: '새로운 데이터에서의 기대 예측 오차를 편향의 제곱, 분산, 환원 불가능 오차의 세 항으로 나누어 분석하는 통계학적 분해 방법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: 'Bagging', abbr: 'Random Forest', definition: '고분산 모델(예: 깊은 결정 트리)을 여러 개 학습시켜 평균을 내어 편향은 거의 유지한 채 분산을 줄이는 앙상블 기법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: 'Boosting', abbr: 'XGBoost', definition: '약한 모델을 순차적으로 학습시키되 이전 모델의 잔차를 다음 모델이 타겟으로 삼아 체계적 오차를 반복적으로 교정함으로써 편향을 줄이는 앙상블 기법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: '사후 일치성', abbr: 'posterior consistency', definition: '데이터가 충분히 많아지면 초기 사전분포의 선택과 무관하게 사후분포가 동일한 값으로 수렴하는 성질이다.', chapters: ['5.1'], category: '기타' },
    { book: 'stats', term: '가상 관측', abbr: 'pseudo-observations', definition: '베이즈 추론에서 사전분포의 모수를 "데이터를 보기 전에 이미 관측한 것처럼" 해석한 가상의 관측값이다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '정규화 상수', abbr: 'normalizing constant', definition: '베이즈 정리에서 분모에 해당하는 P(data) 항으로, θ에 대한 적분으로 계산되며 θ와 무관하여 사후분포를 확률로 정규화하는 역할을 한다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '켤레 사전분포', abbr: 'conjugate prior', definition: '주어진 우도와 결합했을 때 사후분포가 사전분포와 동일한 분포 족에 속하게 만드는 사전분포이다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '번인', abbr: 'burn-in', definition: 'MCMC 체인이 사후분포에 수렴하기 전, 시작점에 의존하는 초기 샘플을 버리는 기간이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: '변분 추론', abbr: 'Variational Inference, VI', definition: '사후분포를 다루기 쉬운 간단한 분포(보통 정규분포)로 근사하여 추정하는 방법으로, MCMC보다 정확도는 낮지만 속도가 빠르고 대규모 파라미터에 확장 가능한 베이지안 추론 기법이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'ESS', abbr: 'Effective Sample Size', definition: 'MCMC 샘플의 자기상관을 고려해 계산한 유효 샘플 수로, 수렴 진단 지표 중 하나이며 최소 400 이상이 권장된다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'MCMC', abbr: 'Markov Chain Monte Carlo', definition: '사후분포의 정규화 상수를 모르는 상태에서도 확률 비율만을 이용해 해당 분포로부터 샘플을 추출하는 마르코프 연쇄 기반 몬테카를로 방법이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'Stan', abbr: 'PyStan', definition: 'Hamiltonian Monte Carlo(HMC) 기반의 고성능 MCMC 샘플링을 제공하는 베이지안 모델링 라이브러리로, Python에서는 PyStan 인터페이스로 사용한다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: '고정 기간 설계', abbr: 'Fixed Horizon', definition: 'A/B 테스트에서 사전에 필요한 샘플 수와 기간을 정해두고, 그 기간이 끝날 때까지 중간 결과를 확인하지 않고 종료 시점에 한 번만 검정하는 실험 설계 방식이다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '순차 검정', abbr: 'Sequential Testing', definition: '실험 중간에 결과를 반복적으로 확인하면서도 누적된 거짓 양성 위험을 통제하기 위해 유의수준 α를 보정하는 검정 방법이다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '윈저화', abbr: 'Winsorization', definition: '데이터의 극단값을 상하위 특정 백분위수(예: 상하위 1%) 지점의 값으로 대체하여 이상치의 영향을 줄이는 방법으로, 값을 삭제하지 않으므로 표본 크기가 보존된다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '기대 위험', abbr: 'true risk', definition: '모델이 학습에 쓰이지 않은 새로운 데이터에 대해 가질 것으로 기대되는 평균 손실로, 교차검증이 추정하고자 하는 대상이다.', chapters: ['6.2'], category: '기타' },
    { book: 'stats', term: '블록 부트스트랩', abbr: 'Block Bootstrap', definition: '시계열처럼 독립성이 위반된 데이터에서 개별 데이터 포인트 대신 연속된 시간 블록 단위로 복원 추출하여, 블록 내부의 시간적 의존성은 보존하면서 블록 간 독립성만 가정하는 부트스트랩 기법이다.', chapters: ['6.2'], category: '기타' },
    { book: 'stats', term: '미분 엔트로피', abbr: 'Differential Entropy', definition: '연속분포에 대해 합 대신 적분으로 정의한 엔트로피로, $h(X) = -\\int p(x) \\log p(x)\\, dx$이며 이산 엔트로피와 달리 음수가 될 수 있다.', chapters: ['6.3'], category: '기타' },
    { book: 'stats', term: '자기정보', abbr: 'Self-information', definition: '어떤 사건이 일어났을 때의 놀라움을 $-\\log p(x)$로 측정한 값으로, 확률이 낮은 사건일수록 큰 값을 가진다.', chapters: ['6.3'], category: '기타' },
    { book: 'stats', term: '차원의 저주', abbr: 'Curse of Dimensionality', definition: '차원이 증가할수록 데이터가 차지해야 할 공간이 기하급수적으로 커져, 동일한 밀도를 유지하려면 필요한 데이터 양이 폭발적으로 늘어나고 거리·이웃 개념이 무의미해지는 현상이다.', chapters: ['6.4'], category: '기타' },
    { book: 'stats', term: '도구 변수', abbr: 'Instrumental Variable, IV', definition: '처리 변수에는 영향을 주지만 결과 변수에는 직접 영향을 주지 않는 외생 변수를 이용해 인과 효과를 추정하는 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '무작위 대조 실험', abbr: 'Randomized Controlled Trial, RCT', definition: '피실험자를 무작위로 처리군과 대조군에 배정하여 혼란 변수를 균형시킴으로써 인과 효과를 가장 확실하게 확립하는 실험 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '성향 점수 매칭', abbr: 'Propensity Score Matching, PSM', definition: '처리를 받을 확률(성향 점수)이 비슷한 처리군과 대조군 개체를 짝지어 비교함으로써 관측된 혼란 변수의 영향을 보정하는 인과추론 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '식별', abbr: 'Identification', definition: '관측 가능한 데이터 분포만으로 인과 효과를 표현하는 공식이 존재하는지를 판별하는 문제이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '이중차분법', abbr: 'Difference-in-Differences, DiD', definition: '처리 전후와 처리/대조 그룹 간 차이의 차이를 이용해 인과 효과를 추정하는 방법으로, 평행 추세 가정을 전제로 한다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '회귀 불연속', abbr: 'Regression Discontinuity Design, RDD', definition: '처리 여부를 결정하는 임계값 근처에서 발생하는 결과의 불연속적 변화를 이용해 인과 효과를 추정하는 준실험적 방법이다.', chapters: ['6.5'], category: '기타' },

    // ===== claude 자리 자동 추출 + definition v2 =====
    { book: 'claude', term: '모놀리식 커널', abbr: 'monolithic kernel', definition: '운영체제의 모든 핵심 서비스(프로세스 관리, 메모리 관리, 파일 시스템, 장치 드라이버 등)를 하나의 커널 공간에서 통합 실행하는 커널 구조이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '에이전트 루프', abbr: 'agent loop', definition: '에이전트가 목표 달성을 위해 관찰, 추론, 행동, 결과 확인의 과정을 반복적으로 수행하는 순환 구조이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '운영체제', abbr: 'OS', definition: '운영체제(OS)는 컴퓨터 하드웨어와 응용 프로그램 사이에서 자원을 관리하고 사용자에게 실행 환경을 제공하는 시스템 소프트웨어이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '비동기 제너레이터', abbr: 'async generator', definition: '값을 비동기적으로 하나씩 생성하여 반환하는 함수로, async 함수와 제너레이터의 특성을 결합해 await와 yield를 함께 사용할 수 있다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '비동기 프로그래밍', abbr: 'asynchronous programming', definition: '작업의 완료를 기다리지 않고 다른 작업을 동시에 수행할 수 있도록 하여, I/O 대기 시간 동안에도 프로그램이 멈추지 않고 효율적으로 실행되도록 하는 프로그래밍 방식이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '이벤트 루프', abbr: 'event loop', definition: '비동기 작업의 완료를 감시하며 대기 중인 콜백을 순차적으로 실행 큐에 넣어 처리하는 단일 스레드 기반의 실행 메커니즘이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '태스크', abbr: 'Task', definition: '태스크는 시스템이나 사용자가 수행해야 할 하나의 독립적인 작업 단위이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '커스텀 훅', abbr: 'custom hook', definition: '리액트의 내장 훅들을 조합하여 재사용 가능한 로직으로 추출한 사용자 정의 함수이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: '함수형 컴포넌트', abbr: 'functional component', definition: '함수형 컴포넌트는 자바스크립트 함수 형태로 정의되며, props를 인자로 받아 JSX를 반환하는 리액트 컴포넌트이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: '판별 유니온', abbr: 'discriminated union', definition: '공통 필드(태그)의 리터럴 값으로 어떤 변형(variant)인지 구분할 수 있는 객체 타입들의 유니온이다.', chapters: ['0.4'], category: '기타' },
    { book: 'claude', term: '팩토리 패턴', abbr: 'factory pattern', definition: '객체 생성 로직을 별도의 메서드나 클래스로 분리하여, 클라이언트가 구체적인 클래스를 직접 지정하지 않고도 객체를 생성할 수 있게 하는 디자인 패턴이다.', chapters: ['0.5'], category: '기타' },
    { book: 'claude', term: '부트스트랩', abbr: 'Bootstrap', definition: '부트스트랩은 시스템이나 프로그램이 최소한의 초기 코드만으로 스스로를 단계적으로 로드하여 실행 가능한 상태로 만드는 과정이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '빠른 경로', abbr: 'fast path', definition: '일반적이고 빈번하게 발생하는 상황을 빠르게 처리하기 위해 최적화된 실행 경로이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '실행 전 훅', abbr: 'preAction hook', definition: '액션이 실행되기 직전에 호출되어 입력값 검증, 권한 확인, 전처리 등을 수행하는 훅이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: 'REPL', abbr: 'Read-Eval-Print Loop', definition: '사용자가 입력한 코드를 즉시 읽어(Read) 평가하고(Eval) 결과를 출력(Print)하는 과정을 반복(Loop)하는 대화형 프로그래밍 실행 환경이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: 'vLLM', abbr: 'Llama-3.1 70B', definition: '도구를 _두 번 이상_ 호출 (`find . -name \'*.py\'`, `ls *.py`) 하면서 _덜 정리된 응답_.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: '429', abbr: 'rate limit', definition: '클라이언트가 일정 시간 내 허용된 요청 횟수를 초과했을 때 서버가 반환하는 HTTP 상태 코드이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: '529', abbr: 'server overloaded', definition: '서버가 과부하 상태로 인해 요청을 처리할 수 없음을 나타내는 비표준 HTTP 상태 코드이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: 'Server-Sent Events', abbr: 'SSE', definition: '서버가 HTTP 연결을 통해 클라이언트에게 실시간으로 데이터를 단방향으로 전송할 수 있게 해주는 웹 표준 기술이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: '1급 시민', abbr: 'first-class citizen', definition: '변수에 할당, 함수의 인자로 전달, 함수의 반환값으로 사용 등 다른 모든 값과 동등하게 취급될 수 있는 대상이다.', chapters: ['3.1'], category: '기타' },
    { book: 'claude', term: '교차 관심사', abbr: 'cross-cutting concerns', definition: '애플리케이션의 여러 모듈에 걸쳐 공통적으로 적용되어야 하는 로깅, 보안, 트랜잭션 관리 등과 같은 부가 기능적 관심사를 의미한다.', chapters: ['3.1'], category: '기타' },
    { book: 'claude', term: '가상 스크롤', abbr: 'virtual scroll', definition: '화면에 보이는 영역의 항목만 실제로 렌더링하여 대량의 리스트를 효율적으로 표시하는 기법이다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: '지시문', abbr: 'Instructions', definition: '지시문은 사용자가 모델에게 수행해야 할 작업이나 따라야 할 규칙을 자연어로 전달하는 명령 형태의 입력이다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'PTL 재시도', abbr: 'max 3', definition: 'PTL(Pick To Light) 작업 중 오류 발생 시 최대 3회까지 재시도를 허용하는 규칙이다.', chapters: ['7.4'], category: '기타' },
    { book: 'claude', term: '분기와 합류', abbr: 'fork-join', definition: '하나의 실행 흐름을 여러 개의 병렬 작업으로 분기시킨 뒤, 모든 작업이 완료되기를 기다려 다시 하나의 흐름으로 합치는 병렬 처리 패턴이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '죽은 코드 제거', abbr: 'dead-code elimination', definition: '프로그램 실행 결과에 영향을 주지 않는 코드를 식별하여 제거하는 컴파일러 최적화 기법이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '심층 방어', abbr: 'defense in depth', definition: '단일 보안 통제에 의존하지 않고 여러 계층의 방어 수단을 중첩하여, 한 계층이 뚫리더라도 다른 계층이 공격을 차단하도록 하는 보안 전략이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'Vertex', abbr: 'GCP', definition: 'Google Cloud Platform에서 제공하는 통합 머신러닝 플랫폼으로, 모델 학습·배포·관리 및 생성형 AI 서비스를 지원한다.', chapters: ['9.1', '10.5'], category: '기타' },
];

export default glossary;
