import type { Book } from './books';

export interface GlossaryEntry {
    book: Book;
    term: string;
    abbr?: string;
    definition: string;
    chapters: string[];
    category: string;
}

const glossary: GlossaryEntry[] = [
    // ===== 공정 =====
    { book: 'semi', term: '웨이퍼', abbr: 'Wafer', definition: '반도체 소자를 만드는 원판형 실리콘 기판. 직경 300 mm(12인치)가 현재 표준.', chapters: ['1.1', '1.2'], category: '공정' },
    { book: 'semi', term: '팹', abbr: 'Fab', definition: '반도체 제조 공장(Fabrication Facility). 클린룸 환경에서 웨이퍼를 가공.', chapters: ['1.1', '1.3'], category: '공정' },
    { book: 'semi', term: '파운드리', abbr: 'Foundry', definition: '칩 설계 없이 제조만 전문으로 하는 기업. TSMC, 삼성 파운드리 등.', chapters: ['1.1'], category: '공정' },
    { book: 'semi', term: '팹리스', abbr: 'Fabless', definition: '팹 없이 칩을 설계만 하는 기업. Qualcomm, NVIDIA 등.', chapters: ['1.1'], category: '공정' },
    { book: 'semi', term: '잉곳', abbr: 'Ingot', definition: '단결정 실리콘 원기둥. 초크랄스키(CZ)법으로 성장시킨 후 슬라이싱하여 웨이퍼를 얻는다.', chapters: ['1.2'], category: '공정' },
    { book: 'semi', term: '클린룸', abbr: 'Clean Room', definition: '파티클을 극도로 제어한 무진 공간. 반도체 팹의 핵심 환경.', chapters: ['1.3'], category: '공정' },
    { book: 'semi', term: '산화', abbr: 'Oxidation', definition: '실리콘 표면에 SiO₂(산화막)를 형성하는 공정. 게이트 절연막, 소자 분리에 사용.', chapters: ['1.4'], category: '공정' },
    { book: 'semi', term: '증착', abbr: 'Deposition', definition: '기판 위에 박막을 형성하는 공정. CVD(화학기상증착), PVD(물리기상증착), ALD(원자층증착) 등.', chapters: ['1.4', '1.5'], category: '공정' },
    { book: 'semi', term: 'CVD', abbr: 'Chemical Vapor Deposition', definition: '화학 기상 증착. 가스 반응으로 기판에 박막을 형성.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: 'ALD', abbr: 'Atomic Layer Deposition', definition: '원자층 증착. 한 번에 원자 1층씩 증착하여 극도로 균일한 박막 형성.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: 'PVD', abbr: 'Physical Vapor Deposition', definition: '물리 기상 증착. 스퍼터링 등으로 금속 박막을 증착.', chapters: ['1.5'], category: '공정' },
    { book: 'semi', term: '식각', abbr: 'Etching', definition: '원하지 않는 부분의 재료를 제거하는 공정. 건식(플라즈마)과 습식(화학 용액)으로 구분.', chapters: ['1.6'], category: '공정' },
    { book: 'semi', term: '플라즈마', abbr: 'Plasma', definition: '이온화된 기체. 건식 식각과 PECVD에서 반응성 이온을 생성하는 핵심 매체.', chapters: ['1.6'], category: '공정' },
    { book: 'semi', term: 'CMP', abbr: 'Chemical Mechanical Planarization', definition: '화학적·기계적 연마로 웨이퍼 표면을 평탄화하는 공정.', chapters: ['1.7'], category: '공정' },
    { book: 'semi', term: '이온 주입', abbr: 'Ion Implantation', definition: '불순물 이온을 가속하여 반도체에 주입하는 도핑 공정.', chapters: ['1.8'], category: '공정' },
    { book: 'semi', term: '어닐링', abbr: 'Annealing', definition: '이온 주입 후 결정 格子를 복구하고 불순물을 활성화하는 열처리 공정.', chapters: ['1.8'], category: '공정' },
    { book: 'semi', term: 'BEOL', abbr: 'Back-End-Of-Line', definition: '트랜지스터 형성 후 금속 배선과 비아를 만드는 후공정.', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: 'FEOL', abbr: 'Front-End-Of-Line', definition: '트랜지스터를 형성하는 전공정(산화, 이온주입, 게이트 형성).', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: '비아', abbr: 'Via', definition: '서로 다른 금속 배선층을 수직으로 연결하는 구멍/플러그.', chapters: ['1.9'], category: '공정' },
    { book: 'semi', term: '세정', abbr: 'Cleaning', definition: '웨이퍼 표면의 파티클, 유기물, 금속 오염을 제거하는 공정. SC-1/SC-2 용액 사용.', chapters: ['1.3'], category: '공정' },
    { book: 'semi', term: '패키징', abbr: 'Packaging', definition: '완성된 칩을 외부와 연결하고 보호하는 후공정. 와이어 본딩, 플립칩 등.', chapters: ['1.10'], category: '공정' },
    { book: 'semi', term: '트랜지스터', abbr: 'MOSFET', definition: '반도체의 기본 스위칭 소자. 게이트 전압으로 소스-드레인 간 전류를 제어.', chapters: ['1.1', '1.9'], category: '공정' },

    // ===== 리소그래피 =====
    { book: 'semi', term: '포토리소그래피', abbr: 'Photolithography', definition: '빛을 이용해 마스크의 패턴을 웨이퍼의 포토레지스트에 전사하는 핵심 공정.', chapters: ['2.1'], category: '리소그래피' },
    { book: 'semi', term: '포토레지스트', abbr: 'Photoresist, PR', definition: '빛에 반응하는 감광성 고분자. 노광 후 현상하여 패턴을 형성.', chapters: ['2.2'], category: '리소그래피' },
    { book: 'semi', term: 'EUV', abbr: 'Extreme Ultraviolet', definition: '극자외선(13.5 nm 파장). 7 nm 이하 노드의 핵심 리소그래피 광원.', chapters: ['2.3', '2.12', '5.1'], category: '리소그래피' },
    { book: 'semi', term: 'ArF', definition: '불화아르곤 엑시머 레이저(193 nm 파장). 현재 DUV 리소의 주력 광원.', chapters: ['2.3'], category: '리소그래피' },
    { book: 'semi', term: 'KrF', definition: '크립톤 플루오라이드 엑시머 레이저(248 nm 파장). 성숙 노드에서 사용.', chapters: ['2.3'], category: '리소그래피' },
    { book: 'semi', term: 'NA', abbr: 'Numerical Aperture', definition: '개구수. 렌즈가 빛을 모으는 능력의 척도. NA가 클수록 해상도가 높아진다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: 'DOF', abbr: 'Depth of Focus', definition: '초점 심도. 허용 가능한 포커스 범위. NA가 올라가면 DOF가 줄어든다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: '프로세스 윈도우', abbr: 'Process Window', definition: 'Dose와 Focus의 허용 범위. 이 안에서만 CD 스펙을 만족한다.', chapters: ['2.6'], category: '리소그래피' },
    { book: 'semi', term: 'OPC', abbr: 'Optical Proximity Correction', definition: '광근접보정. 광학 왜곡을 보상하기 위해 마스크 패턴을 미리 변형하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'RET', abbr: 'Resolution Enhancement Technology', definition: '해상도 향상 기술. OPC, PSM, OAI 등의 총칭.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'ILT', abbr: 'Inverse Lithography Technology', definition: '역리소그래피. 원하는 웨이퍼 패턴에서 역으로 최적 마스크를 계산하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'PSM', abbr: 'Phase Shift Mask', definition: '위상 반전 마스크. 인접 패턴에 위상차를 주어 해상도를 향상시키는 기법.', chapters: ['2.7', '2.8'], category: '리소그래피' },
    { book: 'semi', term: 'OAI', abbr: 'Off-Axis Illumination', definition: '비축 조명. 회절차수를 최적으로 포착하기 위해 조명 형태를 변형하는 기법.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: '마스크', abbr: 'Reticle', definition: '회로 패턴이 새겨진 석영 판. 빛이 통과하여 웨이퍼에 패턴을 전사.', chapters: ['2.8'], category: '리소그래피' },
    { book: 'semi', term: '펠리클', abbr: 'Pellicle', definition: '마스크 표면 보호용 얇은 필름. 파티클이 패턴면에 닿는 것을 방지.', chapters: ['2.8', '2.12'], category: '리소그래피' },
    { book: 'semi', term: 'Overlay', definition: '오버레이. 연속된 리소 레이어 간의 정렬 오차. 서브 나노미터 제어가 필요.', chapters: ['2.9', '2.10'], category: '리소그래피' },
    { book: 'semi', term: 'CPE', abbr: 'Corrections Per Exposure', definition: '노광 필드별 독립 보정. 고차 Overlay 변동을 흡수.', chapters: ['2.10'], category: '리소그래피' },
    { book: 'semi', term: 'CD', abbr: 'Critical Dimension', definition: '핵심 치수(선폭). 패턴의 실제 폭. CD 균일도(CDU)가 수율을 좌우.', chapters: ['2.11'], category: '리소그래피' },
    { book: 'semi', term: 'CDU', abbr: 'CD Uniformity', definition: 'CD 균일도. 웨이퍼 내/간, 필드 내/간, 로트 간 변동을 계층적으로 분해하여 관리.', chapters: ['2.11'], category: '리소그래피' },
    { book: 'semi', term: 'MEEF', abbr: 'Mask Error Enhancement Factor', definition: '마스크 오차가 웨이퍼에서 얼마나 증폭되는지 나타내는 계수.', chapters: ['2.7'], category: '리소그래피' },
    { book: 'semi', term: 'CD-SAXS', abbr: 'Small-Angle X-ray Scattering', definition: 'X선 소각 산란 기반 CD 측정. 3D 패턴 프로파일을 비파괴로 계측.', chapters: ['2.12'], category: '리소그래피' },
    { book: 'semi', term: '확률적 결함', abbr: 'Stochastic Defect', definition: 'EUV 광자 수 부족으로 발생하는 통계적 패턴 결함. Shot Noise에 의한 랜덤 변동.', chapters: ['2.12'], category: '리소그래피' },
    { book: 'semi', term: '멀티패터닝', abbr: 'Multi-Patterning', definition: 'EUV 이전에 미세 피치를 달성하기 위해 여러 번 노광하는 기법. LELE, SADP 등.', chapters: ['2.13'], category: '리소그래피' },
    { book: 'semi', term: 'SADP', abbr: 'Self-Aligned Double Patterning', definition: '자기 정렬 이중 패터닝. 스페이서를 이용해 피치를 절반으로 줄이는 기법.', chapters: ['2.13'], category: '리소그래피' },
    { book: 'semi', term: 'High-NA', definition: 'NA 0.55의 차세대 EUV 시스템. 비등방(Anamorphic) 광학계 사용.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: 'DSA', abbr: 'Directed Self-Assembly', definition: '블록 공폴리머의 자기 조립을 이용한 차세대 패터닝 기술.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: 'NIL', abbr: 'Nanoimprint Lithography', definition: '나노임프린트. 몰드로 물리적 압착하여 패턴을 전사. 광학 불필요.', chapters: ['5.1'], category: '리소그래피' },
    { book: 'semi', term: '회절', abbr: 'Diffraction', definition: '빛이 패턴 가장자리에서 퍼지는 현상. 리소그래피 해상도의 근본적 제한 요인.', chapters: ['2.6', '2.7'], category: '리소그래피' },
    { book: 'semi', term: '보성 곡선', abbr: 'Bossung Curve', definition: 'Focus에 따른 CD 변화를 보여주는 곡선. 프로세스 윈도우 분석의 핵심 도구.', chapters: ['2.6'], category: '리소그래피' },

    // ===== 수율/계측 =====
    { book: 'semi', term: '수율', abbr: 'Yield', definition: '웨이퍼에서 양품 칩의 비율. 반도체 비즈니스의 핵심 지표.', chapters: ['3.1'], category: '수율/계측' },
    { book: 'semi', term: 'SPC', abbr: 'Statistical Process Control', definition: '통계적 공정 관리. 관리도로 공정 안정성을 실시간 감시.', chapters: ['3.2'], category: '수율/계측' },
    { book: 'semi', term: 'FDC', abbr: 'Fault Detection & Classification', definition: '장비 센서 데이터로 이상을 자동 탐지하고 분류하는 시스템.', chapters: ['3.3'], category: '수율/계측' },
    { book: 'semi', term: 'APC', abbr: 'Advanced Process Control', definition: '고급 공정 제어. R2R(Run-to-Run) 피드백/피드포워드로 공정을 실시간 보정.', chapters: ['3.5'], category: '수율/계측' },
    { book: 'semi', term: 'VM', abbr: 'Virtual Metrology', definition: '가상 계측. 실측 없이 FDC 데이터로 공정 결과를 예측하는 ML 모델.', chapters: ['3.4'], category: '수율/계측' },
    { book: 'semi', term: 'R2R', abbr: 'Run-to-Run', definition: '웨이퍼(또는 Lot) 단위로 공정 조건을 피드백 보정하는 제어 방식.', chapters: ['3.5'], category: '수율/계측' },
    { book: 'semi', term: 'CD-SEM', definition: '주사 전자 현미경 기반 선폭(CD) 측정 장비.', chapters: ['3.6'], category: '수율/계측' },
    { book: 'semi', term: 'OCD', abbr: 'Optical Critical Dimension', definition: '광학 기반 CD 측정. 산란광 분석으로 비파괴 고속 측정.', chapters: ['3.6'], category: '수율/계측' },
    { book: 'semi', term: 'ADC', abbr: 'Automatic Defect Classification', definition: '자동 결함 분류. SEM 이미지에서 결함 유형을 자동 판별.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: '웨이퍼맵', abbr: 'Wafer Map', definition: '웨이퍼 내 다이별 결함/계측 분포를 2D로 시각화한 맵. 공간 패턴으로 원인 분석.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: 'ADI', abbr: 'After Develop Inspection', definition: '현상 후 검사. 리소 패턴의 결함을 식각 전에 조기 탐지.', chapters: ['3.7'], category: '수율/계측' },
    { book: 'semi', term: 'AEI', abbr: 'After Etch Inspection', definition: '식각 후 검사. 최종 패턴의 결함 검출.', chapters: ['3.7'], category: '수율/계측' },

    // ===== AI/ML =====
    { book: 'semi', term: 'XGBoost', definition: 'Gradient Boosted Decision Trees. 반도체 VM/FDC에서 가장 많이 쓰이는 ML 알고리즘.', chapters: ['4.2'], category: 'AI/ML' },
    { book: 'semi', term: 'SHAP', abbr: 'SHapley Additive exPlanations', definition: '피처의 기여도를 정량적으로 분해하는 모델 해석 기법.', chapters: ['4.2', '4.4'], category: 'AI/ML' },
    { book: 'semi', term: '피처 엔지니어링', abbr: 'Feature Engineering', definition: '도메인 지식 기반으로 ML 입력 피처를 설계하는 과정. Focus², Dose×두께 등.', chapters: ['4.2'], category: 'AI/ML' },
    { book: 'semi', term: '시간 기반 분할', abbr: 'Temporal Split', definition: '학습/검증 데이터를 시간 순서로 분할하여 데이터 누수를 방지하는 방법.', chapters: ['4.3'], category: 'AI/ML' },
    { book: 'semi', term: 'RI', abbr: 'Reliability Index', definition: '신뢰 지수. VM 예측의 신뢰도를 0~1로 정량화. RI > 0.7이면 예측 신뢰.', chapters: ['4.3'], category: 'AI/ML' },
    { book: 'semi', term: '이상 탐지', abbr: 'Anomaly Detection', definition: '정상에서 벗어난 데이터를 자동 감지. Autoencoder, Isolation Forest 등 사용.', chapters: ['3.3', '4.6'], category: 'AI/ML' },
    { book: 'semi', term: 'MLOps', definition: 'ML 모델의 학습→배포→모니터링→재학습 전체 생명주기 관리 체계.', chapters: ['4.5'], category: 'AI/ML' },
    { book: 'semi', term: 'CNN', abbr: 'Convolutional Neural Network', definition: '합성곱 신경망. 웨이퍼맵 패턴 분류, OPC 가속 등에 사용.', chapters: ['4.6'], category: 'AI/ML' },
    { book: 'semi', term: 'LSTM', abbr: 'Long Short-Term Memory', definition: '장단기 기억 네트워크. FDC Trace의 시계열 패턴 학습에 사용.', chapters: ['4.6'], category: 'AI/ML' },
    { book: 'semi', term: '전이 학습', abbr: 'Transfer Learning', definition: '한 팹/장비에서 학습한 모델을 다른 팹/장비에 적응시키는 기법.', chapters: ['4.7'], category: 'AI/ML' },
    { book: 'semi', term: 'Federated Learning', definition: '연합 학습. 데이터를 공유하지 않고 모델 파라미터만 교환하여 학습.', chapters: ['4.7'], category: 'AI/ML' },
    { book: 'semi', term: 'RL', abbr: 'Reinforcement Learning', definition: '강화 학습. 에이전트가 환경과 상호작용하며 보상을 최대화하는 정책을 학습.', chapters: ['4.8'], category: 'AI/ML' },
    { book: 'semi', term: 'Bayesian Optimization', abbr: 'BO', definition: '베이지안 최적화. 서로게이트 모델(GP)과 획득 함수로 효율적 전역 최적화.', chapters: ['4.8'], category: 'AI/ML' },
    { book: 'semi', term: 'LLM', abbr: 'Large Language Model', definition: '대규모 언어 모델. GPT 등. 반도체에서는 엔지니어 어시스턴트로 활용.', chapters: ['4.9'], category: 'AI/ML' },
    { book: 'semi', term: 'SMILE', definition: 'Smart Manufacturing Intelligence & Learning Engine. 반도체 AI 통합 파이프라인.', chapters: ['4.10'], category: 'AI/ML' },
    { book: 'semi', term: '디지털 트윈', abbr: 'Digital Twin', definition: '실제 팹/장비의 가상 복제본. 물리+ML 모델로 시뮬레이션과 최적화.', chapters: ['5.2'], category: 'AI/ML' },
    { book: 'semi', term: 'Foundation Model', definition: '대규모 사전학습 모델. 반도체 Foundation Model은 여러 팹 데이터로 사전학습 후 소량 적응.', chapters: ['5.2'], category: 'AI/ML' },
    { book: 'semi', term: '데이터 드리프트', abbr: 'Data Drift', definition: '시간에 따라 입력 데이터의 분포가 변하는 현상. 모델 재학습 트리거.', chapters: ['4.5'], category: 'AI/ML' },

    // ===== 장비/기업 =====
    { book: 'semi', term: 'ASML', definition: '네덜란드 반도체 노광장비 기업. EUV 스캐너 독점 공급.', chapters: ['2.4', '2.12'], category: '장비/기업' },
    { book: 'semi', term: '스캐너', abbr: 'Scanner', definition: '스텝 앤 스캔(Step & Scan) 방식의 노광 장비. 슬릿으로 마스크를 주사하며 노광.', chapters: ['2.4'], category: '장비/기업' },
    { book: 'semi', term: 'KLA', definition: '반도체 검사/계측 장비 기업. 결함 검사와 패턴 인식 분야 선도.', chapters: ['3.7', '5.3'], category: '장비/기업' },
    { book: 'semi', term: 'TSMC', definition: '대만 파운드리 기업. 세계 최대 반도체 위탁 생산.', chapters: ['1.1', '5.3'], category: '장비/기업' },
    { book: 'semi', term: 'cuLitho', definition: 'NVIDIA의 GPU 기반 OPC/리소 시뮬레이션 가속 플랫폼. 40배 이상 속도 향상.', chapters: ['2.7', '5.2'], category: '장비/기업' },
    { book: 'semi', term: 'Applied Materials', abbr: 'AMAT', definition: '세계 최대 반도체 장비 기업. 식각, 증착, CMP 장비 공급.', chapters: ['5.3'], category: '장비/기업' },

    // ===== stats 자리 자동 추출 + definition v2 =====
    { book: 'stats', term: '가중평균', abbr: 'Weighted Mean', definition: '각 값에 서로 다른 중요도(가중치)를 부여하여 계산하는 평균으로, 가중치의 합으로 정규화된 가중합이다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '비강건', abbr: 'Non-robust', definition: '통계량이 이상치나 극단값에 의해 크게 영향을 받아 값이 쉽게 왜곡되는 성질을 말한다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '왜도', abbr: 'Skewness', definition: '분포의 비대칭 정도를 수치화한 통계량으로, 표준화된 편차의 세제곱 평균으로 계산되어 어느 쪽 꼬리가 더 무거운지를 나타낸다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '후버 손실', abbr: 'Huber Loss', definition: '작은 오차에는 제곱(MSE), 큰 오차에는 절대값(MAE)을 적용하여 두 손실 함수의 장점을 결합한 회귀 손실 함수이다.', chapters: ['1.1'], category: '기타' },
    { book: 'stats', term: '변동계수', abbr: 'Coefficient of Variation, CV', definition: '표준편차를 평균으로 나눈 값(보통 백분율로 표기)으로, 단위나 척도가 다른 데이터의 상대적 변동성을 비교할 때 쓰는 무차원 지표이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '분산', abbr: 'Variance', definition: '데이터가 평균에서 얼마나 떨어져 있는지를 제곱한 편차의 평균으로 측정한 값으로, 데이터의 흩어진 정도를 나타내는 지표이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '중심극한정리', abbr: 'CLT', definition: '독립인 확률변수들의 표본 평균이 표본 크기가 커질수록 정규분포에 가까워지며 그 분산이 원 분산을 표본 크기로 나눈 값으로 줄어든다는 통계학의 정리이다.', chapters: ['1.2', '2.4'], category: '기타' },
    { book: 'stats', term: '평균절대편차', abbr: 'Mean Absolute Deviation, MAD', definition: '각 데이터가 평균에서 떨어진 거리의 절대값을 평균낸 값으로, 산포도를 직관적으로 나타내는 지표이다.', chapters: ['1.2'], category: '기타' },
    { book: 'stats', term: '분위 회귀', abbr: 'Quantile Regression', definition: '조건부 평균이 아닌 조건부 백분위수를 예측하는 회귀 기법으로, 핀볼 손실을 손실함수로 사용한다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제1사분위수', abbr: 'Q1', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 25% 지점에 해당하는 값으로, 25번째 백분위수(p25)와 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제2사분위수', abbr: 'Q2', definition: '데이터를 크기 순으로 정렬했을 때 아래에서 50% 지점에 해당하는 값으로, 중앙값과 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '제3사분위수', abbr: 'Q3', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 75% 지점에 해당하는 값으로, 75번째 백분위수와 같다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '핀볼 손실', abbr: 'Pinball Loss', definition: '분위 회귀에서 사용되는 비대칭 손실함수로, 예측값이 실제값보다 작을 때와 클 때 가중치를 τ와 (1-τ)로 다르게 부여하여 조건부 백분위수를 추정하도록 한다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: 'p번째 백분위수', abbr: 'p-th percentile', definition: '데이터를 크기 순으로 정렬했을 때 아래에서부터 p%에 해당하는 값이다.', chapters: ['1.3'], category: '기타' },
    { book: 'stats', term: '공분산', abbr: 'Covariance', definition: '두 변수가 평균으로부터 같은 방향으로 함께 움직이는 경향을 측정하는 값으로, 피어슨 상관계수의 분자에 해당한다.', chapters: ['1.4'], category: '기타' },
    { book: 'stats', term: '상호정보량', abbr: 'Mutual Information, MI', definition: '한 변수를 알았을 때 다른 변수에 대한 불확실성이 얼마나 줄어드는지를 측정하는 정보이론 기반 지표로, 선형·비선형·단조·비단조를 가리지 않고 두 변수 간의 모든 형태의 의존 관계를 포착한다.', chapters: ['1.4', '6.3'], category: '기타' },
    { book: 'stats', term: '바이올린 플롯', abbr: 'Violin Plot', definition: '박스플롯의 요약 통계 위에 KDE를 겹쳐 분포의 형태까지 함께 보여주는 시각화 기법이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: '커널 밀도 추정', abbr: 'Kernel Density Estimation, KDE', definition: '각 데이터 포인트에 부드러운 커널(보통 가우시안)을 얹어 합산함으로써 연속적인 밀도 곡선을 추정하는 방법이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: 'QQ플롯', abbr: 'Quantile-Quantile Plot', definition: '데이터의 표본 분위수와 정규분포의 이론 분위수를 비교하여, 데이터가 정규분포에서 얼마나 어디서 벗어나는지를 시각적으로 진단하는 플롯이다.', chapters: ['1.5'], category: '기타' },
    { book: 'stats', term: '베이지안', abbr: 'Bayesian', definition: '확률을 불확실성에 대한 주관적 믿음의 정도로 해석하는 통계학 학파이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '빈도주의', abbr: 'Frequentist', definition: '확률을 무한히 반복된 시행에서의 상대 빈도로 해석하는 통계학 학파이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '사전확률', abbr: 'Prior', definition: '데이터를 관측하기 전에 가지고 있는 가설에 대한 초기 믿음의 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '사후확률', abbr: 'Posterior', definition: '데이터를 관측한 후 베이즈 정리로 업데이트된 가설에 대한 믿음의 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '여사건의 법칙', abbr: 'Complement Rule', definition: '어떤 사건이 일어나지 않을 확률은 1에서 그 사건이 일어날 확률을 뺀 값과 같다는 법칙, 즉 P(Aᶜ) = 1 - P(A)이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '우도', abbr: 'Likelihood', definition: '특정 가설이 참이라고 가정했을 때 주어진 데이터가 관측될 확률이다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '콜모고로프 공리', abbr: 'Kolmogorov Axioms', definition: '확률론의 모든 법칙이 유도되는 세 가지 기본 규칙으로, 비음성($P(A) \\geq 0$), 정규화($P(\\Omega) = 1$), 그리고 서로 배반인 사건에 대한 가법성($P(A \\cup B) = P(A) + P(B)$)으로 구성된다.', chapters: ['2.1'], category: '기타' },
    { book: 'stats', term: '경험적 위험 최소화', abbr: 'Empirical Risk Minimization, ERM', definition: '알 수 없는 기대 손실 대신 학습 데이터에 대한 경험적 손실(표본 평균)을 최소화하여 모델을 학습시키는 원리이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '누적분포함수', abbr: 'CDF, Cumulative Distribution Function', definition: '확률변수가 특정 값 이하일 확률을 그 값의 함수로 나타낸 것으로, $F(x) = P(X \\leq x)$로 정의되며 이산·연속 확률변수 모두에 적용 가능하다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '코시 분포', abbr: 'Cauchy distribution', definition: '꼬리가 매우 두꺼워 적분이 발산하므로 기댓값이 존재하지 않는 연속확률분포이며, 표본 평균이 특정 값으로 수렴하지 않는다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률밀도함수', abbr: 'PDF, Probability Density Function', definition: '연속 확률변수에서 특정 값 근처의 확률 밀도를 나타내는 함수로, 구간에 대해 적분하면 그 구간의 확률이 된다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률변수', abbr: 'Random Variable', definition: '표본공간의 각 결과를 실수로 대응시키는 함수로, 어떤 결과가 실현될지는 모르지만 값을 부여하는 규칙 자체는 고정되어 있다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '확률질량함수', abbr: 'PMF, Probability Mass Function', definition: '이산 확률변수에서 각 값 x에 대해 그 값이 나올 확률 P(X = x)를 직접 지정하는 함수이다.', chapters: ['2.2'], category: '기타' },
    { book: 'stats', term: '베르누이 분포', abbr: 'Bernoulli Distribution', definition: '성공(1) 또는 실패(0) 두 가지 결과만 가지는 확률변수의 분포로, 단일 파라미터 p에 의해 P(X=1)=p, P(X=0)=1-p로 결정된다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '최대우도추정', abbr: 'Maximum Likelihood Estimation, MLE', definition: '관측된 데이터가 나올 확률(우도)을 최대화하는 분포의 파라미터를 찾는 통계적 추정 방법이다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '포아송 회귀', abbr: 'Poisson Regression', definition: '카운트 데이터를 예측하기 위해 타겟이 포아송 분포를 따른다고 가정하고, 로그 링크 함수를 통해 선형 결합을 비음수 기대값으로 변환하는 일반화 선형 모델이다.', chapters: ['2.3'], category: '기타' },
    { book: 'stats', term: '라플라스 분포', abbr: 'Laplace Distribution', definition: '평균을 중심으로 양쪽으로 지수적으로 감소하는 대칭 확률분포로, 뾰족한 봉우리 형태를 가지며 L1 정규화(Lasso)의 사전분포로 사용된다.', chapters: ['2.4'], category: '기타' },
    { book: 'stats', term: '부트스트랩', abbr: 'Bootstrap', definition: '원래 데이터에서 복원 추출로 같은 크기의 새 데이터셋을 반복 생성하여 통계량의 표본 분포를 시뮬레이션으로 직접 근사하는 기법이다.', chapters: ['2.5'], category: '기타' },
    { book: 'stats', term: '표본 분포', abbr: 'sampling distribution', definition: '어떤 통계량(평균, 중앙값, 회귀 계수 등)을 같은 크기의 표본에서 반복적으로 계산했을 때 얻어지는 값들의 분포이다.', chapters: ['2.5', '3.1'], category: '기타' },
    { book: 'stats', term: '표준오차', abbr: 'Standard Error, SE', definition: '표본 평균이 표본마다 얼마나 흩어지는지를 나타내는 척도로, 모표준편차를 표본 크기의 제곱근으로 나눈 값(σ/√n)이며 표본 크기가 커질수록 작아진다.', chapters: ['2.5'], category: '기타' },
    { book: 'stats', term: '몬테카를로', abbr: 'Monte Carlo', definition: '난수 샘플링을 통해 해석적으로 풀기 어려운 적분이나 기댓값을 근사하는 수치 계산 기법이다.', chapters: ['2.6'], category: '기타' },
    { book: 'stats', term: '모수', abbr: 'Parameter', definition: '모집단의 특성을 나타내는 고정된 값으로, 보통 그리스 문자로 표기하며 우리가 추정하고자 하는 미지의 상수이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '모집단', abbr: 'Population', definition: '관심의 대상이 되는 전체 집합으로, 통계적 추론이 추정하고자 하는 대상이며 대부분의 경우 직접 관측할 수 없다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '불편추정량', abbr: 'unbiased estimator', definition: '추정량의 기댓값이 추정 대상인 모수와 일치하는 추정량으로, 반복 추정 시 평균적으로 참값에 맞는 성질을 갖는다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '통계량', abbr: 'Statistic', definition: '표본에서 계산한 값으로 모수를 추정하는 데 쓰이며, 표본에 따라 달라지는 확률변수이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '통계적 추론', abbr: 'statistical inference', definition: '관측된 표본 데이터를 바탕으로 직접 관측할 수 없는 모집단의 특성을 추측하는 통계적 방법론이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '표본', abbr: 'Sample', definition: '모집단에서 뽑은 부분집합으로, 실제로 관측하여 분석에 사용하는 데이터이다.', chapters: ['3.1'], category: '기타' },
    { book: 'stats', term: '구간추정', abbr: 'Interval Estimation', definition: '모수의 참값이 포함될 것으로 추정되는 범위를 신뢰구간으로 제시하여 추정의 불확실성을 함께 보고하는 방법이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '신뢰구간', abbr: 'Confidence Interval', definition: '모수의 참값이 포함될 것으로 기대되는 범위를 신뢰수준과 함께 제시하여 점추정의 불확실성을 정량화한 구간이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '신용구간', abbr: 'credible interval', definition: '베이즈 통계에서 모수에 부여된 사후확률분포를 바탕으로 "모수가 특정 범위에 있을 확률이 95%"라고 직접 해석할 수 있는 구간이다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '예측구간', abbr: 'Prediction Interval', definition: '새로운 관측값이 포함될 범위를 추정하는 구간으로, 모수의 불확실성에 개별 관측값의 변동성까지 더하기 때문에 신뢰구간보다 항상 넓다.', chapters: ['3.2'], category: '기타' },
    { book: 'stats', term: '가설검정', abbr: 'Hypothesis Testing', definition: '관측된 차이나 효과가 우연으로 설명 가능한지를 판단하기 위해, 귀무가설을 세우고 이를 기각할 수 있는지 통계적으로 검증하는 프레임워크이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '검정 통계량', abbr: 'test statistic', definition: '귀무가설 하에서 관측 결과가 얼마나 극단적인지를 하나의 숫자로 요약한 값이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '검정력 분석', abbr: 'power analysis', definition: '원하는 검정력을 달성하기 위해 필요한 표본 크기를 실험 전에 계산하는 절차이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '귀류법', abbr: 'proof by contradiction', definition: '어떤 명제를 증명하기 위해 그 부정을 가정한 뒤 모순을 이끌어내어 원래 명제를 입증하는 논증 방식이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '사후 검정력 분석', abbr: 'post-hoc power analysis', definition: '실험이 끝난 후 관측된 효과 크기를 바탕으로 검정력을 계산하는 분석으로, p-value의 단순 변환에 불과해 새로운 정보를 제공하지 않는다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '제1종 오류', abbr: 'Type I', definition: '귀무가설이 참(효과 없음)인데 이를 기각하여 효과가 있다고 잘못 판단하는 오류로, 그 확률을 α(유의수준)로 나타낸다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '제2종 오류', abbr: 'Type II', definition: '귀무가설이 실제로 거짓(효과가 있음)인데도 이를 기각하지 못해 효과가 없다고 잘못 판단하는 오류로, ML 분류의 False Negative에 해당한다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '효과 크기', abbr: 'Effect Size', definition: '두 그룹 간 차이의 크기를 표준화하여 나타낸 값으로, 검정력과 필요한 표본 크기를 결정하는 핵심 요인이다.', chapters: ['3.3'], category: '기타' },
    { book: 'stats', term: '단측검정', abbr: 'one-sided test', definition: '차이의 방향(더 크다 또는 더 작다)을 사전에 지정하여 한쪽 방향의 효과만 검정하는 가설검정 방식이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '양측검정', abbr: 'two-sided test', definition: '두 집단의 평균이 서로 다른지(μ_A ≠ μ_B)를 방향 구분 없이 검정하는 방법이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '짝 내 변동', abbr: 'within-pair variation', definition: '대응 검정에서 같은 짝(쌍) 내부의 두 관측값 사이에 나타나는 변동으로, 짝 간 공통 요인이 상쇄된 후 남는 순수한 처리 효과 차이를 반영한다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '합동 비율', abbr: 'pooled proportion', definition: '두 그룹의 비율이 같다는 귀무가설 하에서, 전체 데이터를 합쳐 하나로 추정한 비율로 $\\hat{p} = (x_A + x_B)/(n_A + n_B)$로 계산한다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: 'z-검정', abbr: 'z-test', definition: '모표준편차 σ가 알려져 있다는 가정 하에 통계량 z = (x̄ - μ₀)/(σ/√n)을 표준정규분포 N(0,1)과 비교하여 모평균에 대한 가설을 검정하는 방법이다.', chapters: ['3.4'], category: '기타' },
    { book: 'stats', term: '분모', abbr: 'MSW', definition: 'ANOVA F-통계량의 분모로, 각 그룹 내에서 데이터가 자기 그룹 평균으로부터 떨어진 정도를 나타내는 그룹 내 변동(평균 제곱)이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '분산분석', abbr: 'Analysis of Variance, ANOVA', definition: '셋 이상의 그룹 평균이 서로 같은지를 한 번의 검정으로 비교하여, t-검정을 반복할 때 발생하는 거짓 양성 증가 문제를 피하는 통계 기법이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '분자', abbr: 'MSB', definition: 'F-통계량의 분자로, 각 그룹 평균이 전체 평균에서 얼마나 떨어져 있는지를 나타내는 그룹 간 평균 제곱(Mean Square Between)이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '사후 검정', abbr: 'post-hoc test', definition: 'ANOVA 등에서 전체적으로 유의미한 차이가 발견된 후, 구체적으로 어떤 그룹 쌍들 간에 차이가 있는지를 확인하기 위해 수행하는 추가 검정이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'ANOVA', abbr: 'Analysis of Variance', definition: '셋 이상의 그룹 평균이 모두 같은지를 그룹 간 변동과 그룹 내 변동의 비(F-통계량)로 한 번에 검정하는 방법이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SSB', abbr: 'Between', definition: '그룹 간 평균의 차이로 설명되는 분산으로, 각 그룹 평균과 전체 평균의 편차 제곱합에 그룹 크기를 가중하여 합한 값이다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SST', abbr: 'Total', definition: '전체 데이터의 평균을 기준으로 한 편차 제곱합으로, 데이터 전체의 총 변동을 나타낸다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: 'SSW', abbr: 'Within', definition: '각 그룹 내부에서 개별 관측치들이 그룹 평균으로부터 벗어난 변동의 제곱합으로, 그룹 내 개별 변동에 의한 분산을 나타낸다.', chapters: ['3.5'], category: '기타' },
    { book: 'stats', term: '가족별 오류율', abbr: 'Family-Wise Error Rate, FWER', definition: '여러 번의 가설검정을 수행할 때 적어도 하나 이상의 거짓 양성이 발생할 확률로, 검정 횟수가 m이고 각 검정이 독립이면 1 - (1-α)^m로 계산된다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '기댓값', abbr: 'E', definition: '확률 변수가 반복 실험에 걸쳐 평균적으로 취하는 값으로, 분모가 0이 되는 경우 등 정의되지 않는 상황을 자연스럽게 처리할 수 있게 해주는 통계적 개념이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '다중검정 문제', abbr: 'Multiple Testing Problem', definition: '여러 번의 통계 검정을 수행할수록 우연히 유의미한 결과(거짓 양성)가 발생할 확률이 증가하는 문제이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '위발견율', abbr: 'False Discovery Rate, FDR', definition: '다중 검정에서 유의미하다고 판정한 것들 중 거짓 양성이 차지하는 비율의 기댓값이다.', chapters: ['3.6'], category: '기타' },
    { book: 'stats', term: '가우스-마르코프 정리', abbr: 'Gauss-Markov Theorem', definition: '선형성·오차 기댓값 0·등분산·무상관의 네 가정 하에서 OLS 추정량이 모든 선형 불편추정량 중 분산이 가장 작다(BLUE)는 것을 보장하는 정리이다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '닫힌 형태', abbr: 'closed-form', definition: '반복적 최적화 없이 유한한 수학 연산(덧셈, 곱셈, 역행렬 등)만으로 정확한 해를 한 번에 구할 수 있는 형태이다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '정규방정식', abbr: 'normal equation', definition: 'OLS 추정량을 구하는 해 $\\hat{\\beta} = (X^TX)^{-1}X^Ty$를 도출하는 방정식 $X^TX\\beta = X^Ty$로, 잔차 벡터가 $X$의 열공간에 직교한다는 기하학적 의미를 담고 있다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '최소제곱법', abbr: 'Ordinary Least Squares, OLS', definition: '잔차 제곱합(RSS)을 최소화하는 회귀계수를 구하는 방법으로, 정규 노이즈 가정 하에서 최대우도추정과 동치이며 (XᵀX)⁻¹Xᵀy라는 닫힌 형태의 해를 갖는다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: 'BLUE', abbr: 'Best Linear Unbiased Estimator', definition: '가우스-마르코프 정리의 가정 하에서 OLS 추정량이 갖는 성질로, 모든 선형 불편추정량 중 분산이 가장 작은(가장 효율적인) 추정량을 의미한다.', chapters: ['4.1'], category: '기타' },
    { book: 'stats', term: '결정 경계', abbr: 'decision boundary', definition: '분류 모델에서 예측 클래스가 갈리는 경계로, 로지스틱 회귀의 경우 $P(Y=1)=0.5$가 되는 지점인 $w^Tx + b = 0$의 초평면이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '보정', abbr: 'Calibration', definition: '모델이 출력한 확률이 실제 확률에 얼마나 가까운지를 나타내는 속성이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '소프트맥스', abbr: 'Softmax', definition: 'K개의 로짓을 입력받아 각 값을 지수화한 뒤 합으로 나누어, 모든 클래스의 확률이 0~1이고 합이 1이 되도록 변환하는 다중 클래스용 활성화 함수이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '오즈비', abbr: 'Odds Ratio', definition: '로지스틱 회귀에서 설명변수가 1 단위 증가할 때 오즈가 변하는 배수로, 계수에 지수함수를 취한 값(e^β)으로 정의된다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '카테고리 분포', abbr: 'Categorical Distribution', definition: '다중 클래스 분류에서 각 클래스가 발생할 확률을 나타내는 이산 확률분포로, 베르누이 분포를 K개 범주로 일반화한 것이다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '피셔 정보 행렬', abbr: 'Fisher Information Matrix', definition: '로그우도 함수의 2차 미분(헤시안)의 기댓값에 음수를 취한 행렬로, MLE 추정량의 점근적 분산을 결정하여 표준오차 계산의 기반이 된다.', chapters: ['4.3'], category: '기타' },
    { book: 'stats', term: '가우시안', abbr: 'Gaussian', definition: '평균과 분산으로 정의되는 종 모양의 연속 확률분포로, 베이즈 회귀에서 계수의 사전분포로 사용되어 L2 정규화와 동등한 효과를 낸다.', chapters: ['4.4'], category: '기타' },
    { book: 'stats', term: 'MAP', abbr: 'L2', definition: '가우시안 사전분포 하에서 사후확률을 최대화하는 추정으로, Ridge 회귀(L2 정규화)와 정확히 동일한 해를 준다.', chapters: ['4.4'], category: '기타' },
    { book: 'stats', term: '이중 하강', abbr: 'Double Descent', definition: '모델 복잡도를 보간 임계점 이상으로 극단적으로 키울 때, 테스트 오차가 일단 증가한 뒤 다시 감소하여 전통적 U자 곡선을 벗어나는 현상이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: '편향-분산 분해', abbr: 'Bias-Variance Decomposition', definition: '기대 예측 오차를 편향의 제곱, 분산, 환원 불가능 오차의 세 항으로 분해하여 모델의 일반화 성능을 설명하는 통계적 분석 기법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: 'Bagging', abbr: 'Random Forest', definition: '고분산 모델(예: 깊은 결정 트리)을 여러 개 학습시켜 평균 내는 방식으로, 편향은 거의 유지한 채 분산을 줄이는 앙상블 기법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: 'Boosting', abbr: 'XGBoost', definition: '약한 모델을 순차적으로 학습시키되 각 모델이 이전 모델의 잔차를 타겟으로 학습하여 체계적 오차를 반복 교정함으로써 편향을 줄이는 앙상블 기법이다.', chapters: ['4.5'], category: '기타' },
    { book: 'stats', term: '사후 일치성', abbr: 'posterior consistency', definition: '데이터가 충분히 많아지면 어떤 합리적인 사전분포를 쓰든 사후분포가 동일한 곳으로 수렴하는 성질이다.', chapters: ['5.1'], category: '기타' },
    { book: 'stats', term: '가상 관측', abbr: 'pseudo-observations', definition: '켤레 사전분포의 하이퍼파라미터를 실제 데이터를 보기 전에 미리 관측한 가상의 표본처럼 해석하는 개념이다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '정규화 상수', abbr: 'normalizing constant', definition: '베이즈 정리의 분모 P(data)로, 사후분포가 확률분포가 되도록 전체 적분을 1로 만드는 역할을 하며 θ와 무관한 상수이다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '켤레 사전분포', abbr: 'conjugate prior', definition: '주어진 우도와 결합했을 때 사후분포가 사전분포와 동일한 분포 족에 속하게 만드는 사전분포이다.', chapters: ['5.2'], category: '기타' },
    { book: 'stats', term: '번인', abbr: 'burn-in', definition: 'MCMC 체인이 사후분포에 수렴하기 전의 초기 샘플 구간으로, 시작점에 의존하므로 버려야 하는 기간이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: '변분 추론', abbr: 'Variational Inference, VI', definition: '사후분포를 간단한 분포(보통 정규)로 근사하여 추정하는 베이지안 추론 기법으로, MCMC보다 정확도는 떨어지지만 속도가 빠르고 대규모 파라미터에 확장 가능하다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'ESS', abbr: 'Effective Sample Size', definition: 'MCMC 샘플의 자기상관을 고려해 환산한 유효 샘플 수로, 수렴 진단 시 최소 400 이상이 권장된다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'MCMC', abbr: 'Markov Chain Monte Carlo', definition: '사후분포의 정규화 상수를 모르는 채 확률 비율만으로 그 분포에서 샘플을 뽑아 적분을 근사하는 마르코프 연쇄 기반 몬테카를로 기법이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: 'Stan', abbr: 'PyStan', definition: 'Stan(PyStan)은 Hamiltonian Monte Carlo(HMC) 기반의 고성능 MCMC 샘플링을 제공하는 베이지안 통계 모델링 라이브러리이다.', chapters: ['5.4'], category: '기타' },
    { book: 'stats', term: '고정 기간 설계', abbr: 'Fixed Horizon', definition: 'A/B 테스트에서 사전에 필요한 샘플 수와 기간을 정한 뒤, 그 기간이 끝날 때까지 중간 결과를 보지 않고 종료 시점에 한 번만 검정하는 실험 설계 방식이다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '순차 검정', abbr: 'Sequential Testing', definition: '실험 중간에 결과를 여러 번 확인할 수 있도록 허용하되, 반복 검정으로 인한 거짓 양성 증가를 막기 위해 유의수준 α를 보정하는 검정 방법이다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '윈저화', abbr: 'Winsorization', definition: '데이터의 극단값을 상하위 특정 백분위수(예: 1%) 값으로 대체하여 이상치의 영향을 완화하는 방법으로, 표본을 삭제하지 않아 크기가 보존된다.', chapters: ['6.1'], category: '기타' },
    { book: 'stats', term: '기대 위험', abbr: 'true risk', definition: '모델이 학습에 사용되지 않은 새로운 데이터에서 보일 평균적인 손실로, 교차검증이 추정 대상으로 삼는 일반화 성능 지표이다.', chapters: ['6.2'], category: '기타' },
    { book: 'stats', term: '블록 부트스트랩', abbr: 'Block Bootstrap', definition: '시계열처럼 독립성이 위반된 데이터에서 개별 포인트 대신 연속된 시간 블록 단위로 복원 추출하여, 블록 내 시간적 의존성은 보존하고 블록 간에만 독립을 가정하는 부트스트랩 기법이다.', chapters: ['6.2'], category: '기타' },
    { book: 'stats', term: '미분 엔트로피', abbr: 'Differential Entropy', definition: '연속확률분포에 대해 합을 적분으로 바꾸어 정의한 엔트로피로, $h(X) = -\\int p(x) \\log p(x)\\, dx$로 표현되며 이산 엔트로피와 달리 음수가 될 수 있다.', chapters: ['6.3'], category: '기타' },
    { book: 'stats', term: '자기정보', abbr: 'Self-information', definition: '어떤 사건이 일어났을 때의 놀라움의 정도를 $I(x) = -\\log p(x)$로 정량화한 값으로, 확률이 낮은 사건일수록 큰 값을 가진다.', chapters: ['6.3'], category: '기타' },
    { book: 'stats', term: '차원의 저주', abbr: 'Curse of Dimensionality', definition: '차원이 증가할수록 데이터가 필요한 양이 기하급수적으로 늘어나고 공간이 희박해져, 거리 기반 모델 등 기존 기법의 성능이 급격히 저하되는 현상이다.', chapters: ['6.4'], category: '기타' },
    { book: 'stats', term: '도구 변수', abbr: 'Instrumental Variable, IV', definition: '처리 변수 X에는 영향을 주지만 결과 변수 Y에는 직접 영향을 주지 않는 변수를 활용해 인과 효과를 추정하는 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '무작위 대조 실험', abbr: 'Randomized Controlled Trial, RCT', definition: '피실험자를 처리군과 대조군에 무작위로 배정하여 관측되지 않은 혼란 변수까지 균형시킴으로써 처리의 인과 효과를 확립하는, 인과추론의 황금 표준이 되는 실험 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '성향 점수 매칭', abbr: 'Propensity Score Matching, PSM', definition: '처리를 받을 확률(성향 점수)이 비슷한 처리군과 대조군 개체를 짝지어 비교함으로써 관측 데이터에서 인과 효과를 추정하는 방법이다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '식별', abbr: 'Identification', definition: '관측 가능한 데이터의 분포만으로 인과 효과를 표현할 수 있는지를 따지는 문제이며, 식별이 되어야 비로소 관측 데이터로부터 인과 효과를 계산하는 공식이 존재한다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '이중차분법', abbr: 'Difference-in-Differences, DiD', definition: '처리 전후 시점과 처리/대조 그룹 간 차이의 차이를 비교하여 인과 효과를 추정하는 방법으로, 평행 추세 가정을 전제로 한다.', chapters: ['6.5'], category: '기타' },
    { book: 'stats', term: '회귀 불연속', abbr: 'Regression Discontinuity Design, RDD', definition: '처리 여부를 결정하는 임계값 근처에서 발생하는 결과 변수의 불연속적 변화를 이용해 인과 효과를 추정하는 방법이다.', chapters: ['6.5'], category: '기타' },

    // ===== claude 자리 자동 추출 v3 (영어 단독 패턴 추가, def AI 일괄) =====
    { book: 'claude', term: '도구 사용 루프', abbr: 'tool-use loop', definition: '에이전트가 도구를 호출하고 그 결과를 받아 다음 행동을 결정하는 과정을 반복적으로 수행하는 실행 사이클이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '마이크로커널', abbr: 'microkernel', definition: '운영체제의 핵심 기능만 최소한으로 커널에 두고, 나머지 서비스는 사용자 공간에서 별도 프로세스로 실행하는 커널 구조이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '모놀리식 커널', abbr: 'monolithic kernel', definition: '운영체제의 모든 핵심 서비스(파일 시스템, 장치 드라이버, 메모리 관리 등)를 하나의 커널 공간에서 통합적으로 실행하는 커널 구조이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '에이전트 루프', abbr: 'agent loop', definition: '에이전트가 목표 달성을 위해 관찰, 사고, 행동을 반복적으로 수행하는 순환 실행 구조이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '운영체제', abbr: 'OS', definition: '운영체제(OS)는 컴퓨터 하드웨어와 응용 프로그램 사이에서 자원을 관리하고 사용자와 시스템 간의 인터페이스를 제공하는 시스템 소프트웨어이다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '하네스', abbr: 'harness', definition: '하네스(harness)는 여러 전선이나 케이블을 하나로 묶어 정리한 배선 다발로, 신호나 전력을 효율적으로 전달하기 위해 사용된다.', chapters: ['0.1'], category: '기타' },
    { book: 'claude', term: '비동기 제너레이터', abbr: 'async generator', definition: '비동기 작업의 결과를 순차적으로 yield하여 for await...of 구문으로 순회할 수 있게 해주는 함수이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '비동기 프로그래밍', abbr: 'asynchronous programming', definition: '작업이 완료될 때까지 기다리지 않고 다른 작업을 동시에 수행할 수 있도록 하는 프로그래밍 방식이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '이벤트 루프', abbr: 'event loop', definition: '비동기 작업의 완료를 감지하고 콜백을 순차적으로 처리하는 단일 스레드 기반의 반복 실행 메커니즘이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '제너레이터', abbr: 'generator', definition: '호출될 때마다 yield 문을 통해 값을 하나씩 생성하여 반환하며, 실행 상태를 유지하는 특수한 함수이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '코루틴', abbr: 'coroutine', definition: '실행을 일시 중단하고 재개할 수 있어 비선점적 멀티태스킹을 가능하게 하는 함수이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '태스크', abbr: 'Task', definition: '태스크는 시스템이나 사용자가 수행해야 하는 하나의 독립적인 작업 단위이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '프로미스', abbr: 'Promise', definition: '비동기 작업의 최종 완료 또는 실패를 나타내는 객체로, 미래에 사용 가능한 값을 표현한다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: 'JS Promise', definition: 'JS Promise는 자바스크립트에서 비동기 작업의 최종 완료 또는 실패를 나타내는 객체이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: 'Python coroutine', definition: 'async def로 정의되어 호출 시 즉시 실행되지 않고 await를 통해 일시 중단 및 재개가 가능한 비동기 실행 단위이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: 'single-threaded', definition: '하나의 스레드에서 순차적으로 작업을 실행하여 동시에 둘 이상의 연산을 처리하지 않는 방식이다.', chapters: ['0.2'], category: '기타' },
    { book: 'claude', term: '재조정', abbr: 'reconciliation', definition: '재조정(reconciliation)은 서로 다른 시스템이나 기록 간의 데이터를 비교·대조하여 차이를 식별하고 일치시키는 과정이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: '커스텀 훅', abbr: 'custom hook', definition: '리액트의 내장 훅을 조합하여 재사용 가능한 로직을 캡슐화한, use로 시작하는 이름의 사용자 정의 함수이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: '함수형 컴포넌트', abbr: 'functional component', definition: '자바스크립트 함수 형태로 정의되며 props를 입력받아 UI를 반환하는 리액트 컴포넌트이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: 'cleanup', definition: 'cleanup은 작업이나 프로세스가 종료된 후 사용된 리소스를 해제하고 시스템을 원래 상태로 복구하는 정리 작업이다.', chapters: ['0.3'], category: '기타' },
    { book: 'claude', term: 'Ink', definition: 'Ink는 종이나 다른 표면에 글씨를 쓰거나 그림을 그리기 위해 사용되는 색소를 포함한 액체 또는 반죽 형태의 물질이다.', chapters: ['0.3', '1.2', '4.2'], category: '기타' },
    { book: 'claude', term: 'React', definition: 'React는 사용자 인터페이스(UI)를 구축하기 위한 컴포넌트 기반의 자바스크립트 라이브러리이다.', chapters: ['0.3', '1.2'], category: '기타' },
    { book: 'claude', term: 'Textual', definition: 'Textual은 텍스트 형태로 표현되거나 텍스트에 기반한 데이터 또는 정보를 의미한다.', chapters: ['0.3', '1.2', '5.1'], category: '기타' },
    { book: 'claude', term: '타입 가드', abbr: 'type guard', definition: '특정 코드 블록 내에서 변수의 타입을 더 구체적인 타입으로 좁혀주는 런타임 검사 표현식이다.', chapters: ['0.4'], category: '기타' },
    { book: 'claude', term: '판별 유니온', abbr: 'discriminated union', definition: '공통 필드(판별자)의 값으로 어떤 변형(variant)인지 구분할 수 있는, 여러 타입의 합집합 타입이다.', chapters: ['0.4'], category: '기타' },
    { book: 'claude', term: '판별자', abbr: 'discriminant', definition: '이차방정식의 근의 종류와 개수를 판별하기 위해 사용하는 값으로, 일반적으로 b²-4ac로 정의된다.', chapters: ['0.4'], category: '기타' },
    { book: 'claude', term: '클로저', abbr: 'closure', definition: '클로저(closure)는 함수가 자신이 정의된 스코프의 변수들을 기억하여, 해당 스코프 밖에서 실행되더라도 그 변수들에 접근할 수 있게 하는 기능이다.', chapters: ['0.5'], category: '기타' },
    { book: 'claude', term: '팩토리 패턴', abbr: 'factory pattern', definition: '객체 생성 로직을 별도의 메서드나 클래스로 캡슐화하여, 클라이언트가 구체적인 클래스를 지정하지 않고도 객체를 생성할 수 있게 하는 디자인 패턴이다.', chapters: ['0.5'], category: '기타' },
    { book: 'claude', term: '만남점', abbr: 'rendezvous', definition: '두 개 이상의 프로세스나 스레드가 특정 지점에서 서로 만나 동기화한 후 실행을 계속하는 동기화 기법이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '메모이제이션', abbr: 'memoization', definition: '메모이제이션은 함수의 호출 결과를 저장해 두었다가 동일한 입력이 들어오면 재계산 없이 저장된 결과를 반환하는 최적화 기법이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '부트스트랩', abbr: 'Bootstrap', definition: '부트스트랩(Bootstrap)은 시스템이나 프로그램이 외부의 도움 없이 자체적인 초기 절차를 통해 스스로 시동·구동되는 과정을 의미한다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '빠른 경로', abbr: 'fast path', definition: '일반적이고 빈번하게 발생하는 경우를 최적화하여 빠르게 처리하도록 설계된 실행 경로이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '선인출', abbr: 'prefetch', definition: '선인출(prefetch)은 프로그램이 필요로 하기 전에 데이터나 명령어를 미리 메모리나 캐시로 가져오는 기법이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: '실행 전 훅', abbr: 'preAction hook', definition: '액션이 실행되기 직전에 호출되어 입력값 검증이나 전처리 등을 수행하는 훅이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: 'REPL', abbr: 'Read-Eval-Print Loop', definition: '사용자가 입력한 코드를 즉시 읽고 평가한 뒤 결과를 출력하는 과정을 반복하는 대화형 프로그래밍 환경이다.', chapters: ['1.1'], category: '기타' },
    { book: 'claude', term: 'async generator', definition: '비동기적으로 값을 하나씩 생성하여 for await...of 등으로 순회할 수 있는 객체를 반환하는 함수이다.', chapters: ['1.2', '2.1', '9.5'], category: '기타' },
    { book: 'claude', term: 'Part 5', definition: 'Part 5는 핸드북의 다섯 번째 부(部)를 가리키는 구분 단위이다.', chapters: ['1.2'], category: '기타' },
    { book: 'claude', term: 'Part 5.2', definition: 'Part 5.2는 핸드북의 특정 세부 항목을 가리키는 절 번호이나, 제공된 본문에 해당 내용이 없어 정의할 수 없다.', chapters: ['1.2'], category: '기타' },
    { book: 'claude', term: 'silent bug', definition: '오류 메시지나 예외를 발생시키지 않고 조용히 잘못된 동작이나 결과를 만들어내어 발견하기 어려운 버그이다.', chapters: ['10.1'], category: '기타' },
    { book: 'claude', term: 'SkillTool', definition: 'SkillTool은 에이전트가 특정 작업을 수행하기 위해 호출할 수 있는 기능 단위의 도구를 스킬 형태로 정의한 것이다.', chapters: ['10.2'], category: '기타' },
    { book: 'claude', term: 'Workspace trust', definition: 'Workspace trust는 신뢰할 수 없는 코드의 자동 실행을 방지하기 위해 워크스페이스(폴더)별로 코드 실행 권한을 부여하거나 제한하는 보안 기능이다.', chapters: ['10.3'], category: '기타' },
    { book: 'claude', term: 'stdio', definition: 'stdio는 표준 입출력(standard input/output)을 의미하며, 프로그램이 콘솔이나 터미널을 통해 데이터를 입력받고 출력하는 표준 스트림이다.', chapters: ['10.4'], category: '기타' },
    { book: 'claude', term: 'Anthropic', definition: 'Anthropic은 AI 안전성 연구를 중심으로 하는 인공지능 기업으로, 대규모 언어 모델 Claude를 개발한다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Anthropic API', definition: 'Anthropic이 제공하는 Claude 모델을 호출하여 애플리케이션에 통합할 수 있도록 하는 프로그래밍 인터페이스이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Bedrock SDK', definition: 'Amazon Bedrock에서 제공하는 다양한 파운데이션 모델을 애플리케이션에서 호출하고 활용할 수 있도록 지원하는 AWS의 공식 개발 도구이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Claude', definition: 'Claude는 Anthropic이 개발한 대규모 언어 모델 기반의 인공지능 어시스턴트이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Claude API', definition: 'Anthropic이 제공하는 Claude 대규모 언어 모델을 프로그래밍 방식으로 호출하여 활용할 수 있게 해주는 인터페이스이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Foundry Azure AD', definition: 'Foundry 플랫폼에서 사용자 인증 및 접근 관리를 위해 사용되는 Azure Active Directory 디렉터리 서비스이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Foundry SDK', definition: 'Foundry SDK는 Foundry 플랫폼의 데이터와 기능을 외부 애플리케이션이나 코드에서 프로그래밍 방식으로 접근하고 활용할 수 있도록 제공되는 개발자 도구 키트이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Gemini', definition: 'Gemini는 구글이 개발한 멀티모달 생성형 AI 모델이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Gemini API', definition: 'Google에서 제공하는 Gemini 생성형 AI 모델을 애플리케이션에서 호출하여 사용할 수 있도록 지원하는 프로그래밍 인터페이스이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Google', definition: 'Google은 검색 엔진을 비롯해 다양한 인터넷 기반 서비스와 제품을 제공하는 글로벌 IT 기업이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'IN', definition: 'IN은 SQL에서 특정 값이 주어진 목록이나 서브쿼리 결과에 포함되는지 확인하는 비교 연산자이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'OpenAI API', definition: 'OpenAI에서 제공하는 GPT 등 인공지능 모델을 외부 애플리케이션에서 호출하여 사용할 수 있도록 지원하는 프로그래밍 인터페이스이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'OUT', definition: 'OUT은 게임이나 경기에서 선수나 팀이 공격 기회를 잃거나 경기장 밖으로 벗어난 상태를 의미한다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'Vertex API', definition: 'Google Cloud에서 제공하는 머신러닝 모델 개발, 배포, 관리를 위한 통합 AI 플랫폼 API이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'vLLM', abbr: 'Llama-3.1 70B', definition: 'vLLM 추론 엔진에서 Llama-3.1 70B 모델을 서빙하는 구성으로, 고처리량 LLM 추론을 위한 대표적인 오픈소스 배포 환경이다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'vLLM API', definition: 'vLLM에서 제공하는 고성능 LLM 추론 및 서빙용 API로, OpenAI 호환 인터페이스를 통해 모델을 호출할 수 있다.', chapters: ['10.5'], category: '기타' },
    { book: 'claude', term: 'AGENT.md frontmatter', definition: 'AGENT.md 파일 상단에 YAML 형식으로 작성되어 문서의 메타데이터(제목, 대상 에이전트, 우선순위 등)를 정의하는 영역이다.', chapters: ['10.6'], category: '기타' },
    { book: 'claude', term: '나쁜 패턴', abbr: 'polling', definition: '변경 사항이나 이벤트를 감지하기 위해 일정한 간격으로 반복해서 상태를 확인하는 비효율적인 방식이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'abort chaining', definition: 'abort chaining은 여러 abort 핸들러나 작업을 연쇄적으로 연결하여, 하나의 취소 신호가 발생하면 연결된 모든 작업이 순차적으로 중단되도록 하는 메커니즘이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'bug-hunt', definition: '소프트웨어나 시스템에 숨어 있는 결함(버그)을 찾아내기 위해 집중적으로 수행하는 탐색 및 테스트 활동이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'collect', definition: '스트림의 요소들을 리스트, 집합, 맵 등의 컬렉션이나 단일 결과로 누적하여 반환하는 종료 연산이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'critical', definition: 'critical은 시스템이나 작업의 성공, 안전, 또는 정상 작동에 필수적이어서 실패 시 심각한 영향을 초래하는 요소나 상태를 의미한다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'fan-in', definition: 'fan-in은 하나의 논리 게이트나 모듈이 입력으로 받을 수 있는 신호 또는 연결의 수를 의미한다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'high', definition: '디지털 신호에서 논리적으로 1에 해당하는 상대적으로 높은 전압 상태이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'low', definition: '값이나 수준, 정도가 기준보다 낮은 상태를 의미한다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'mailbox', definition: '메시지를 수신하여 저장하는 전용 공간으로, 수신자가 읽거나 처리할 때까지 메시지를 보관하는 통신 매커니즘이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'medium', definition: '정보나 데이터를 전달하거나 저장하는 데 사용되는 물리적 또는 기술적 수단이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'peer DM', definition: '동료 직원 간에 일대일로 주고받는 비공식 다이렉트 메시지이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'spawn', definition: '새로운 프로세스나 스레드를 생성하여 실행을 시작하는 동작을 의미한다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: 'wait', definition: 'wait는 특정 조건이 충족되거나 이벤트가 발생할 때까지 프로세스나 스레드의 실행을 일시 중단하는 동작이다.', chapters: ['10.8'], category: '기타' },
    { book: 'claude', term: '대화', abbr: 'conversation', definition: '사용자와 AI 모델이 메시지를 주고받으며 이어가는 일련의 상호작용이다.', chapters: ['2.1'], category: '기타' },
    { book: 'claude', term: '한 턴', abbr: 'turn', definition: '한 턴(turn)은 사용자와 시스템(또는 상대방) 사이에 주고받는 하나의 발화 단위로, 입력과 그에 대한 응답이 한 차례 오가는 과정을 의미한다.', chapters: ['2.1'], category: '기타' },
    { book: 'claude', term: 'Claude Agent SDK', definition: 'Claude Agent SDK는 Anthropic이 제공하는 공식 개발 도구로, Claude를 활용한 자율형 AI 에이전트를 구축할 수 있도록 도구 사용, 파일 조작, 코드 실행 등의 기능을 지원한다.', chapters: ['2.1'], category: '기타' },
    { book: 'claude', term: 'persists across turns', definition: '대화의 여러 턴에 걸쳐 정보나 상태가 계속 유지된다.', chapters: ['2.1'], category: '기타' },
    { book: 'claude', term: 'starts a new turn', definition: '에이전트가 이전 응답을 마치고 새로운 사용자 입력이나 도구 결과를 받아 다음 응답 생성을 시작하는 시점이다.', chapters: ['2.1'], category: '기타' },
    { book: 'claude', term: 'AsyncGenerator', definition: '비동기적으로 값을 하나씩 생성(yield)하여 반환하는 제너레이터로, async for 문을 통해 순회할 수 있는 객체이다.', chapters: ['2.2'], category: '기타' },
    { book: 'claude', term: 'attachment', definition: '메시지나 이메일 등에 함께 첨부되어 전송되는 파일이나 문서이다.', chapters: ['2.2'], category: '기타' },
    { book: 'claude', term: '429', abbr: 'rate limit', definition: '클라이언트가 허용된 요청 속도 한도를 초과했을 때 서버가 반환하는 HTTP 상태 코드이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: '529', abbr: 'server overloaded', definition: '서버가 과부하 상태로 인해 요청을 처리할 수 없음을 나타내는 비표준 HTTP 상태 코드이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: 'autocompact', definition: 'autocompact는 데이터베이스의 단편화된 공간을 자동으로 정리하여 저장 효율을 높이는 기능이다.', chapters: ['2.3', '7.4'], category: '기타' },
    { book: 'claude', term: 'context length exceeded', definition: '입력 토큰 수가 모델이 처리할 수 있는 최대 컨텍스트 길이를 초과하여 발생하는 오류이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: 'Server-Sent Events', abbr: 'SSE', definition: '서버가 HTTP 연결을 통해 클라이언트로 실시간 이벤트를 단방향으로 지속해서 전송할 수 있게 해주는 웹 표준 기술이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: 'transition reason', definition: '워크플로우에서 한 상태에서 다른 상태로 전환될 때 그 전환이 발생한 사유를 나타내는 값이다.', chapters: ['2.3'], category: '기타' },
    { book: 'claude', term: '1급 시민', abbr: 'first-class citizen', definition: '다른 객체들이 일반적으로 사용할 수 있는 모든 연산(변수에 할당, 함수 인자로 전달, 함수의 반환값으로 사용 등)을 동일하게 지원하는 객체이다.', chapters: ['3.1'], category: '기타' },
    { book: 'claude', term: '교차 관심사', abbr: 'cross-cutting concerns', definition: '여러 모듈이나 계층에 걸쳐 공통적으로 적용되어야 하는 부가 기능(로깅, 보안, 트랜잭션 등)을 의미한다.', chapters: ['3.1'], category: '기타' },
    { book: 'claude', term: 'abstractmethod', definition: '추상 클래스에서 하위 클래스가 반드시 구현해야 하는 메서드를 지정하는 데코레이터이다.', chapters: ['3.2'], category: '기타' },
    { book: 'claude', term: 'NTLM', definition: 'NTLM은 사용자 자격 증명을 챌린지-응답 방식으로 검증하는 Microsoft의 인증 프로토콜이다.', chapters: ['3.4'], category: '기타' },
    { book: 'claude', term: 'read', definition: '저장 매체나 입력 장치로부터 데이터를 가져와 메모리로 불러오는 동작이다.', chapters: ['3.4'], category: '기타' },
    { book: 'claude', term: 'blocking sleep', definition: '현재 스레드 또는 태스크의 실행을 지정된 시간 동안 완전히 멈추어, 그 동안 해당 실행 흐름이 다른 작업을 처리하지 못하게 하는 대기 방식이다.', chapters: ['3.5'], category: '기타' },
    { book: 'claude', term: 'Fail-safe', definition: '시스템에 장애가 발생하더라도 안전한 상태를 유지하도록 설계하는 방식이다.', chapters: ['3.5'], category: '기타' },
    { book: 'claude', term: 'tree-sitter', definition: '소스 코드를 빠르고 정확하게 파싱하여 구문 트리를 생성하는 증분 파싱 라이브러리이자 파서 생성 도구이다.', chapters: ['3.5'], category: '기타' },
    { book: 'claude', term: '디스패처', abbr: 'dispatcher', definition: '디스패처는 들어오는 요청이나 이벤트를 적절한 처리기(핸들러)로 분배하고 전달하는 구성 요소이다.', chapters: ['4.1'], category: '기타' },
    { book: 'claude', term: '라우터', abbr: 'router', definition: '라우터는 서로 다른 네트워크 간에 데이터 패킷의 최적 경로를 결정하여 전달하는 네트워크 장비이다.', chapters: ['4.1'], category: '기타' },
    { book: 'claude', term: 'lazy load', definition: '필요한 시점까지 리소스의 로딩을 지연시켜, 초기 로드 시간을 단축하고 성능을 향상시키는 기법이다.', chapters: ['4.2'], category: '기타' },
    { book: 'claude', term: 'capability-based security', definition: '객체에 접근하기 위해 위조 불가능한 권한 토큰(capability)을 소유한 주체에게만 해당 작업을 허용하는 보안 모델이다.', chapters: ['4.3'], category: '기타' },
    { book: 'claude', term: 'Least privilege', definition: '사용자나 프로세스에 작업 수행에 필요한 최소한의 권한만 부여하는 보안 원칙이다.', chapters: ['4.3'], category: '기타' },
    { book: 'claude', term: 'skill', definition: '특정 작업이나 활동을 효과적으로 수행하기 위해 학습과 경험을 통해 습득한 능력이다.', chapters: ['4.3'], category: '기타' },
    { book: 'claude', term: 'dialect', definition: '특정 지역이나 집단에서 사용되는 표준어와 구별되는 언어의 변종이다.', chapters: ['5.1'], category: '기타' },
    { book: 'claude', term: 'diff', definition: '두 파일이나 텍스트 간의 차이점을 비교하여 보여주는 명령어 또는 그 결과물이다.', chapters: ['5.1'], category: '기타' },
    { book: 'claude', term: 'DOM과 무관한 트리 조정기', abbr: 'reconciler', definition: '특정 렌더링 환경(DOM 등)에 의존하지 않고 컴포넌트 트리의 변경 사항을 계산·관리하여 다양한 플랫폼에서 재사용 가능한 조정 엔진이다.', chapters: ['5.1'], category: '기타' },
    { book: 'claude', term: 'concurrent rendering', definition: '렌더링 작업을 중단·재개하거나 우선순위에 따라 처리할 수 있어, UI 응답성을 유지하면서 여러 업데이트를 동시에 처리하는 React의 렌더링 방식이다.', chapters: ['5.2'], category: '기타' },
    { book: 'claude', term: 'reactive attribute', definition: '값이 변경되면 이를 참조하는 컴포넌트가 자동으로 재렌더링되는 반응형 속성이다.', chapters: ['5.2'], category: '기타' },
    { book: 'claude', term: '가상 스크롤', abbr: 'virtual scroll', definition: '화면에 보이는 영역의 항목만 실제로 렌더링하고 나머지는 가상으로 처리하여 대량의 리스트를 효율적으로 표시하는 기법이다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'grow-only', definition: '데이터가 추가만 가능하고 삭제나 수정이 불가능한 자료구조 또는 시스템 특성을 의미한다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'height cache', definition: '블록 헤더의 해시와 높이를 매핑하여 저장함으로써 높이 기반 조회를 빠르게 수행할 수 있도록 하는 캐시이다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'line 617', definition: '본문이 비어 있어 \'line 617\'에 대한 정의를 추출할 수 없다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'overscan', definition: '화면 가장자리가 잘려 보이는 현상을 방지하기 위해 영상 신호를 디스플레이 영역보다 크게 출력하는 기술이다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'paint', definition: 'paint는 표면에 칠하여 보호하거나 장식하기 위해 사용되는 안료, 결합제, 용제 등으로 구성된 유체 상태의 도료이다.', chapters: ['5.3'], category: '기타' },
    { book: 'claude', term: 'API', definition: 'API는 소프트웨어 구성 요소들이 서로 통신하고 상호작용할 수 있도록 정의된 함수, 프로토콜, 도구의 집합이다.', chapters: ['5.4'], category: '기타' },
    { book: 'claude', term: 'Live display', definition: '카메라나 센서가 포착하는 영상을 실시간으로 화면에 출력하여 보여주는 표시 기능이다.', chapters: ['5.4'], category: '기타' },
    { book: 'claude', term: 'width compensation', definition: '가공 시 공구의 반경이나 폭에 의해 발생하는 치수 오차를 보정하기 위해 공구 경로를 보정량만큼 이동시키는 기능이다.', chapters: ['5.4'], category: '기타' },
    { book: 'claude', term: '지시문', abbr: 'Instructions', definition: '지시문은 모델이 수행해야 할 작업이나 따라야 할 규칙을 자연어로 명시한 입력 문장이다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'AppState', definition: 'AppState는 애플리케이션 전반에서 공유되는 전역 상태를 관리하는 객체이다.', chapters: ['6.1', '6.2'], category: '기타' },
    { book: 'claude', term: 'git status', definition: '작업 디렉터리와 스테이징 영역의 현재 상태를 확인하여 변경된 파일, 스테이징된 파일, 추적되지 않는 파일을 보여주는 Git 명령어이다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'managed rules', definition: '보안 서비스 제공자가 사전에 정의하고 유지·관리하는 규칙 집합으로, 일반적인 웹 위협이나 취약점을 자동으로 탐지·차단하는 데 사용된다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'override', definition: '부모 클래스(또는 상위 타입)에서 정의된 메서드를 자식 클래스에서 동일한 시그니처로 재정의하여 동작을 변경하는 것이다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'user role', definition: '시스템 내에서 사용자에게 부여되어 접근 권한과 수행 가능한 작업 범위를 결정하는 역할 구분이다.', chapters: ['6.1'], category: '기타' },
    { book: 'claude', term: 'append-mostly', definition: '데이터의 추가(append) 연산이 대부분을 차지하고, 수정이나 삭제는 거의 발생하지 않는 워크로드 특성을 의미한다.', chapters: ['6.2'], category: '기타' },
    { book: 'claude', term: 'MessagesRef', definition: 'MessagesRef는 채팅 메시지 목록에 대한 참조를 보관하여 컴포넌트 외부에서 메시지 상태에 접근하거나 조작할 수 있도록 하는 참조 객체이다.', chapters: ['6.2'], category: '기타' },
    { book: 'claude', term: 'normalizr', definition: 'Normalizr는 중첩된 JSON 데이터를 스키마 기반으로 정규화하여 엔티티별로 분리된 평탄한 구조로 변환해주는 자바스크립트 라이브러리이다.', chapters: ['6.2'], category: '기타' },
    { book: 'claude', term: 'render projection', definition: '렌더 프로젝션(render projection)은 3D 장면을 2D 화면으로 변환할 때 사용되는 투영 방식이다.', chapters: ['6.2'], category: '기타' },
    { book: 'claude', term: 'Accept edits', definition: 'Claude Code가 파일에 대한 편집을 수행할 때 매번 확인 요청 없이 자동으로 승인되도록 설정하는 권한 모드이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'allow', definition: '특정 동작이나 접근을 허가하거나 가능하게 한다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Always', definition: 'Always는 조건이나 상황에 관계없이 항상, 언제나 적용되거나 발생함을 나타내는 용어이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'block', definition: 'block은 중괄호 {}로 묶인 코드 묶음으로, 변수의 유효 범위(스코프)를 결정하고 제어 흐름 구조의 실행 단위를 구성한다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Bypass Permissions', definition: 'Claude Code에서 모든 명령 실행 시 사용자의 권한 확인을 건너뛰고 자동으로 승인하는 실행 모드이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Default', definition: 'Default는 별도의 설정이나 입력이 없을 때 시스템이 자동으로 적용하는 기본값 또는 기본 동작을 의미한다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'feature gate', definition: '쿠버네티스에서 특정 기능의 활성화 여부를 제어하는 키-값 형태의 설정 플래그이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Plan Mode', definition: 'Plan Mode는 코드를 즉시 수정하지 않고 작업 계획을 먼저 수립하여 사용자에게 검토받은 후 실행하는 작업 모드이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Pydantic', definition: 'Pydantic은 파이썬 타입 힌트를 기반으로 데이터 유효성 검사와 직렬화를 수행하는 라이브러리이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'transcript classifier', definition: '음성이나 텍스트 전사본을 입력받아 사전에 정의된 범주로 분류하는 모델 또는 시스템이다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'Yes / No / Always', definition: '정책이나 옵션의 적용 여부를 나타내는 값으로, Yes는 활성화, No는 비활성화, Always는 예외 없이 항상 적용함을 의미한다.', chapters: ['6.3'], category: '기타' },
    { book: 'claude', term: 'null-byte placeholder', definition: '문자열이나 데이터 영역의 끝을 표시하거나 빈 공간을 채우기 위해 사용하는 값이 0인 바이트(0x00)이다.', chapters: ['6.4'], category: '기타' },
    { book: 'claude', term: 'null-byte sentinel placeholder', definition: '문자열이나 데이터 영역의 끝을 표시하기 위해 사용되는 값이 0인 바이트(0x00) 표식이다.', chapters: ['6.4'], category: '기타' },
    { book: 'claude', term: 'exit code.', definition: '프로세스가 종료될 때 운영체제에 반환하는 정수 값으로, 일반적으로 0은 성공, 0이 아닌 값은 오류를 나타낸다.', chapters: ['6.6'], category: '기타' },
    { book: 'claude', term: 'AWS Bedrock', definition: 'AWS에서 제공하는 완전 관리형 생성형 AI 서비스로, 다양한 파운데이션 모델을 API를 통해 손쉽게 호출하고 활용할 수 있게 해준다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'Azure AD', definition: 'Microsoft에서 제공하는 클라우드 기반 ID 및 액세스 관리 서비스로, 사용자 인증과 권한 부여를 통합 관리한다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'Azure Foundry', definition: 'Azure Foundry는 Microsoft Azure에서 제공하는 AI 모델 및 에이전트를 개발, 배포, 관리할 수 있는 통합 플랫폼이다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'Azure Identity', definition: 'Azure 리소스 및 서비스에 접근할 때 사용자를 식별하고 인증하기 위한 Microsoft Azure의 자격 증명 관리 체계이다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'Bearer token', definition: '토큰을 소지한 자에게 접근 권한을 부여하는 방식의 인증 토큰으로, HTTP 요청 헤더에 포함되어 사용자 신원을 증명한다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'GCP Vertex', definition: 'GCP Vertex는 구글 클라우드 플랫폼에서 제공하는 머신러닝 모델의 학습, 배포, 관리를 통합적으로 지원하는 AI 플랫폼 서비스이다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'lazy import', definition: '모듈이나 패키지를 프로그램 시작 시점이 아니라 실제로 사용되는 시점에 임포트하여 초기 로딩 시간과 메모리 사용을 줄이는 기법이다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'non-streaming', definition: '요청을 처리한 후 전체 결과를 한 번에 반환하는 방식으로, 데이터를 조각 단위로 점진적으로 전송하지 않는다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'streaming', definition: '데이터를 전체가 준비될 때까지 기다리지 않고, 생성되는 즉시 조각 단위로 연속해서 전송하거나 처리하는 방식이다.', chapters: ['7.1'], category: '기타' },
    { book: 'claude', term: 'fail-closed', definition: '시스템이나 구성 요소에 장애가 발생했을 때 접근을 차단하거나 작동을 중지하여 안전한 상태를 유지하는 설계 방식이다.', chapters: ['7.2'], category: '기타' },
    { book: 'claude', term: 'in-process', definition: '동일한 프로세스 내에서 실행되어 별도의 프로세스 간 통신 없이 직접 호출되는 방식이다.', chapters: ['7.2'], category: '기타' },
    { book: 'claude', term: 'MCP', definition: 'MCP(Model Context Protocol)는 AI 모델이 외부 도구, 데이터 소스, 시스템과 표준화된 방식으로 상호작용할 수 있도록 정의한 개방형 프로토콜이다.', chapters: ['7.2'], category: '기타' },
    { book: 'claude', term: 'Fallback 3118', definition: '본문 내용이 비어 있어 Fallback 3118의 정의를 추출할 수 없다.', chapters: ['7.3'], category: '기타' },
    { book: 'claude', term: 'Native App OAuth', definition: '네이티브 앱(모바일·데스크톱 애플리케이션)에서 사용자 인증과 권한 위임을 처리하기 위해 사용되는 OAuth 인증 방식이다.', chapters: ['7.3'], category: '기타' },
    { book: 'claude', term: 'parallel', definition: 'parallel은 여러 작업을 동시에 실행하여 처리 속도를 높이는 병렬 처리 방식이다.', chapters: ['7.3'], category: '기타' },
    { book: 'claude', term: 'stale-while-error', definition: '캐시된 응답의 만료 시간이 지난 후에도, 원본 서버에서 오류가 발생한 경우 지정된 시간 동안 만료된 캐시를 대신 제공하는 HTTP 캐시 제어 지시어이다.', chapters: ['7.3'], category: '기타' },
    { book: 'claude', term: 'WebSocket', definition: 'WebSocket은 클라이언트와 서버 간에 단일 TCP 연결을 통해 양방향 실시간 통신을 가능하게 하는 통신 프로토콜이다.', chapters: ['7.3'], category: '기타' },
    { book: 'claude', term: 'boundary marker', definition: '데이터나 메시지의 시작과 끝을 구분하기 위해 사용되는 특정 문자나 기호이다.', chapters: ['7.4'], category: '기타' },
    { book: 'claude', term: 'PTL 재시도', abbr: 'max 3', definition: 'PTL(Pick To Light) 작업 중 오류 발생 시 최대 3회까지 재시도를 허용하는 정책이다.', chapters: ['7.4'], category: '기타' },
    { book: 'claude', term: 'thinking trace', definition: '모델이 최종 답변을 내놓기 전에 내부적으로 수행하는 추론 과정을 단계별로 기록한 일련의 사고 흐름이다.', chapters: ['7.4'], category: '기타' },
    { book: 'claude', term: 'parallel readlock', definition: '여러 프로세스나 스레드가 동시에 읽기 작업을 수행할 수 있도록 허용하되 쓰기 작업은 차단하는 병렬 읽기 잠금 메커니즘이다.', chapters: ['7.5'], category: '기타' },
    { book: 'claude', term: 'signal propagation', definition: '신경망의 각 층을 거치며 입력 신호(활성값과 기울기)가 전달되는 과정으로, 학습 안정성을 위해 그 분포가 적절히 유지되어야 한다.', chapters: ['7.5'], category: '기타' },
    { book: 'claude', term: 'WSL/Windows boundary', definition: 'WSL 리눅스 환경과 Windows 호스트 환경 사이의 경계로, 파일 시스템·네트워크·프로세스 등이 분리되어 상호 운용 시 변환이나 브리지가 필요한 지점이다.', chapters: ['7.5'], category: '기타' },
    { book: 'claude', term: 'AgentTool', definition: 'AgentTool은 하나의 에이전트를 다른 에이전트가 호출할 수 있는 도구 형태로 래핑하여, 에이전트 간 위임이나 협업을 가능하게 하는 구성 요소이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'ant-only', definition: 'ant 빌드 시스템만을 사용하여 빌드 및 관리되는 프로젝트 형태이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'description', definition: '어떤 대상의 특징, 속성, 상태 등을 글이나 말로 설명한 내용이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'Explore', definition: 'Explore는 알려지지 않은 영역이나 가능성을 조사하고 발견하기 위해 탐색하는 활동이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'gitStatus', definition: 'gitStatus는 Git 작업 디렉터리와 스테이징 영역의 현재 상태를 보여주어 변경된 파일, 스테이징된 파일, 추적되지 않은 파일을 확인하는 명령어이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'haiku', definition: '하이쿠는 5-7-5의 17음으로 이루어진 일본의 짧은 정형시이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'inherit', definition: '상위 클래스나 부모 요소로부터 속성, 메서드, 값 등을 물려받아 그대로 사용하거나 확장한다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'Never delegate understanding.', definition: '코드나 시스템에 대한 이해를 타인이나 도구에 위임하지 않고, 개발자 스스로 직접 파악하고 책임져야 한다는 원칙이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'Plan', definition: 'Plan은 목표 달성을 위해 수행할 작업, 일정, 자원 등을 체계적으로 정리한 실행 계획이다.', chapters: ['8.1'], category: '기타' },
    { book: 'claude', term: 'auto-cleanup', definition: '작업 완료 후 생성된 임시 파일이나 리소스를 자동으로 정리하는 기능이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'cache hit', definition: '요청한 데이터를 캐시에서 바로 찾아 제공하는 경우를 말한다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'cache miss', definition: '캐시에서 요청한 데이터를 찾지 못해 더 느린 하위 저장소에서 가져와야 하는 상황을 말한다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'Coordinator Mode', definition: 'Claude가 직접 작업을 수행하지 않고 여러 하위 에이전트에게 작업을 위임하고 조율하는 운영 방식이다.', chapters: ['8.2', '8.3'], category: '기타' },
    { book: 'claude', term: 'fail-safe defaults', definition: '시스템이 오류, 장애 또는 불확실한 상황에서 기본적으로 가장 안전한 상태나 접근 거부 상태로 동작하도록 설계하는 보안 원칙이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'fresh', definition: 'fresh는 변경 사항이 아직 커밋되지 않았거나 최신 상태로 새로 생성된 데이터나 객체를 의미한다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'in-process teammate', definition: '동일 프로세스 내에서 함께 동작하며 협업하는 구성 요소나 에이전트이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'prompt 대신 거절', abbr: 'deny', definition: '사용자에게 허용 여부를 묻는 프롬프트를 표시하지 않고 해당 작업을 즉시 거부한다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'prompt cache', definition: '반복되는 프롬프트의 처리 결과를 저장해 두었다가 동일하거나 유사한 요청 시 재사용하여 응답 속도와 비용을 절감하는 캐싱 기법이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'root AppState', definition: '애플리케이션 전역에서 공유되는 최상위 상태 객체로, 하위 컴포넌트들이 참조하는 단일 진실 공급원 역할을 한다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'root store', definition: '운영체제나 브라우저 등이 신뢰하는 인증 기관(CA)의 루트 인증서들을 모아 관리하는 저장소이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'task', definition: '특정 목적을 달성하기 위해 수행되어야 하는 작업 단위이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: 'thinking budget', definition: 'thinking budget은 모델이 추론(thinking) 과정에 사용할 수 있는 토큰의 최대 한도를 지정하는 파라미터이다.', chapters: ['8.2'], category: '기타' },
    { book: 'claude', term: '분기와 합류', abbr: 'fork-join', definition: '하나의 실행 흐름을 여러 개의 병렬 작업으로 분기(fork)했다가, 모든 작업이 완료된 후 다시 하나의 흐름으로 합류(join)시키는 병행 처리 패턴이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '우선순위', abbr: 'priority', definition: '여러 작업이나 항목 중에서 어떤 것을 먼저 처리해야 하는지를 결정하는 상대적 중요도나 순서이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '작성자', abbr: 'writer', definition: '작성자는 문서나 콘텐츠를 직접 기획하고 집필하는 사람이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '죽은 코드 제거', abbr: 'dead-code elimination', definition: '프로그램의 실행 결과에 영향을 주지 않는 코드를 컴파일 과정에서 식별하여 제거하는 최적화 기법이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Agent', definition: 'Agent는 환경을 인식하고 목표를 달성하기 위해 자율적으로 의사결정을 내리고 행동을 수행하는 소프트웨어 개체이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Continue vs Spawn', definition: '기존 작업 흐름을 이어서 처리할지(Continue), 별도의 새로운 작업으로 분리해 실행할지(Spawn)를 결정하는 제어 방식이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'coordinator', definition: 'coordinator는 특정 업무나 프로젝트의 진행을 총괄하며 관련된 사람들과 자원을 조율하는 역할을 담당하는 사람이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Fork', definition: 'Fork는 기존 저장소나 프로젝트를 복제하여 독립적으로 수정·발전시킬 수 있는 새로운 사본을 만드는 행위 또는 그 결과물이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'fresh eyes', definition: '기존 작업이나 문서를 처음 접하는 사람의 관점에서 새롭게 바라보며 익숙한 사람이 놓친 문제점이나 개선점을 발견하는 시각이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Join', definition: 'Join은 두 개 이상의 테이블을 특정 컬럼의 값을 기준으로 연결하여 하나의 결과 집합으로 반환하는 연산이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'SendMessage', definition: 'SendMessage는 지정된 윈도우의 윈도우 프로시저에 메시지를 전송하고, 해당 프로시저가 메시지를 처리할 때까지 반환하지 않는 동기 방식의 Windows API 함수이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Spawn fresh', definition: '기존 대화나 컨텍스트를 이어가지 않고 완전히 새로운 상태에서 에이전트나 세션을 처음부터 시작한다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'Synthesis', definition: 'Synthesis는 여러 요소나 정보를 결합하여 새로운 통합된 결과물을 만들어내는 과정이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'TaskStop', definition: 'TaskStop은 실행 중인 작업을 중지시키는 명령 또는 동작이다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: 'user-role messages', definition: '사용자가 모델에게 입력하는 역할(role)이 user로 지정된 메시지로, 대화에서 사용자의 발화나 요청을 나타낸다.', chapters: ['8.3'], category: '기타' },
    { book: 'claude', term: '사내 빌드', abbr: 'ant', definition: 'Apache Ant 빌드 도구를 사용해 사내에서 자체적으로 수행하는 소프트웨어 빌드 절차이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: '심층 방어', abbr: 'defense in depth', definition: '여러 계층의 보안 통제를 중첩하여 하나의 방어 수단이 뚫리더라도 다른 계층이 공격을 차단하도록 하는 보안 전략이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'dead-code-elimination', definition: '컴파일 시점에 실행되지 않거나 결과가 사용되지 않는 코드를 제거하여 최종 산출물의 크기와 실행 비용을 줄이는 최적화 기법이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'GrowthBook', definition: 'GrowthBook은 기능 플래그 관리와 A/B 테스트 실험을 지원하는 오픈소스 실험 플랫폼이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'Mailbox', definition: 'Mailbox는 메시지를 비동기적으로 저장하고 전달하기 위한 통신 매개체로, 송신자가 보낸 메시지를 수신자가 읽을 때까지 보관하는 큐 형태의 저장소이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'rendezvous as filesystem', definition: '프로세스 간 만남(rendezvous) 지점을 파일시스템 경로로 표현하여, 파일을 열거나 접근하는 방식으로 통신 채널을 설정하는 기법이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'Secret guard', definition: 'Secret guard는 코드나 설정 파일에 비밀번호, API 키 등의 민감한 정보가 포함되어 유출되는 것을 사전에 탐지하고 차단하는 보안 메커니즘이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'single-threaded event loop', definition: '단일 스레드에서 이벤트 큐의 작업들을 순차적으로 처리하는 비동기 실행 모델이다.', chapters: ['8.4'], category: '기타' },
    { book: 'claude', term: 'Lazy import', definition: 'Lazy import는 모듈을 프로그램 시작 시점이 아니라 실제로 사용되는 시점에 지연하여 불러오는 기법이다.', chapters: ['9.1', '10.5'], category: '기타' },
    { book: 'claude', term: 'prefix', definition: '식별자나 명령어 등의 앞부분에 붙여 특정한 의미나 범주를 나타내는 접두 문자열이다.', chapters: ['9.1'], category: '기타' },
    { book: 'claude', term: 'Vertex', abbr: 'GCP', definition: 'Google Cloud Platform에서 제공하는 머신러닝 모델 개발, 학습, 배포를 통합 관리하는 AI 플랫폼 서비스이다.', chapters: ['9.1', '10.5'], category: '기타' },
    { book: 'claude', term: 'Anthropic SDK', definition: 'Anthropic에서 제공하는 Claude 모델을 애플리케이션에 통합할 수 있도록 지원하는 공식 소프트웨어 개발 키트이다.', chapters: ['9.2'], category: '기타' },
    { book: 'claude', term: 'stateless', definition: '이전 요청이나 상태 정보를 서버에 저장하지 않고 각 요청을 독립적으로 처리하는 방식이다.', chapters: ['9.2', '9.3'], category: '기타' },
    { book: 'claude', term: 'tool_result', definition: '도구 호출의 실행 결과를 모델에게 다시 전달하기 위해 사용되는 메시지 콘텐츠 유형이다.', chapters: ['9.2'], category: '기타' },
    { book: 'claude', term: 'Bash', definition: 'Unix 계열 운영체제에서 널리 사용되는 명령어 해석기(셸)로, 명령어 실행과 스크립트 작성을 지원한다.', chapters: ['9.3'], category: '기타' },
    { book: 'claude', term: 'Fail-safe by default', definition: '시스템에 장애나 예외 상황이 발생했을 때 기본적으로 안전한 상태(접근 거부, 작동 중지 등)로 전환되도록 설계하는 원칙이다.', chapters: ['9.3'], category: '기타' },
    { book: 'claude', term: 'optional', definition: '값이 존재하거나 존재하지 않을 수 있음을 나타내는 컨테이너 타입으로, null 대신 사용하여 부재 가능성을 명시적으로 표현한다.', chapters: ['9.3'], category: '기타' },
    { book: 'claude', term: 'required', definition: '어떤 작업이나 조건이 반드시 수행되거나 충족되어야 함을 나타내는 필수 요구 사항이다.', chapters: ['9.3'], category: '기타' },
    { book: 'claude', term: 'Write', definition: '데이터를 저장 매체나 메모리에 기록하는 동작이다.', chapters: ['9.3'], category: '기타' },
    { book: 'claude', term: 'fail-closed defaults', definition: '시스템에 오류나 불확실한 상황이 발생했을 때 기본적으로 접근을 차단하거나 안전한 상태로 전환되도록 설정하는 보안 원칙이다.', chapters: ['9.4'], category: '기타' },
    { book: 'claude', term: 'fail-safe', definition: '시스템에 장애가 발생하더라도 안전한 상태를 유지하도록 설계된 방식이다.', chapters: ['9.4'], category: '기타' },
    { book: 'claude', term: 'fnmatch', definition: 'Unix 셸 스타일의 와일드카드 패턴(*, ?, [seq] 등)을 사용하여 파일명이나 문자열의 일치 여부를 검사하는 Python 표준 라이브러리 모듈이다.', chapters: ['9.4'], category: '기타' },
    { book: 'claude', term: 'default false', definition: '별도로 값을 지정하지 않으면 기본적으로 false 값을 가지도록 설정된 상태를 의미한다.', chapters: ['9.5'], category: '기타' },
    { book: 'claude', term: 'generator', definition: '값을 하나씩 생성하여 반환하는 함수로, yield 키워드를 사용해 호출 시마다 다음 값을 순차적으로 만들어내는 이터레이터이다.', chapters: ['9.5'], category: '기타' },
    { book: 'claude', term: 'linked but separate', definition: '서로 연결되어 있지만 독립적으로 분리되어 존재하는 관계를 의미한다.', chapters: ['9.5'], category: '기타' },
    { book: 'claude', term: 'MCP setup', definition: 'MCP(Model Context Protocol) 서버를 구성하여 AI 모델이 외부 도구나 데이터 소스와 연동할 수 있도록 설정하는 작업이다.', chapters: ['9.5'], category: '기타' },
    { book: 'claude', term: 'silent failure', definition: '오류나 예외가 명시적으로 드러나지 않은 채 시스템이 비정상 동작을 계속 수행하는 상태이다.', chapters: ['9.5'], category: '기타' },
    { book: 'claude', term: 'tool_use only', definition: '모델이 사용자에게 직접 답변을 생성하지 않고 오직 도구 호출만 수행하도록 제한하는 동작 모드이다.', chapters: ['9.5'], category: '기타' },
];

export default glossary;
